// Real list contents captured from the official pages on 2026-09-23 by the
// Phase 19 research probe (GitHub Actions), used as parser fixtures so the
// name resolver is tested against the exact spellings those sources use.
// Lists of country names and the EU annex/footnote lines; no other content.
export const ukVisaNationals = [
 "Afghanistan",
 "Albania",
 "Algeria",
 "Angola",
 "Armenia",
 "Azerbaijan",
 "Bangladesh",
 "Belarus",
 "Benin",
 "Bhutan",
 "Bolivia",
 "Bosnia Herzegovina",
 "Botswana",
 "Burkina Faso",
 "Burundi",
 "Cambodia",
 "Cameroon",
 "Cape Verde",
 "Central African Republic",
 "Chad",
 "People’s Republic of China*",
 "Colombia",
 "Comoros",
 "Congo",
 "Côte d’Ivoire (formerly Ivory Coast)",
 "Cuba",
 "Democratic Republic of the Congo",
 "Djibouti",
 "Dominica",
 "Dominican Republic",
 "Ecuador",
 "Egypt",
 "El Salvador",
 "Equatorial Guinea",
 "Eritrea",
 "Eswatini (formerly Swaziland)",
 "Ethiopia",
 "Fiji",
 "Gabon",
 "Gambia",
 "Georgia",
 "Ghana",
 "Guinea",
 "Guinea Bissau",
 "Haiti",
 "Honduras",
 "India",
 "Indonesia",
 "Iran",
 "Iraq",
 "Jamaica",
 "Jordan",
 "Kazakhstan",
 "Kenya",
 "Korea (North)",
 "Kosovo",
 "Kyrgyzstan",
 "Laos",
 "Lebanon",
 "Lesotho",
 "Liberia",
 "Libya",
 "Madagascar",
 "Malawi",
 "Mali",
 "Mauritania",
 "Moldova",
 "Mongolia",
 "Montenegro",
 "Morocco",
 "Mozambique",
 "Myanmar (formerly Burma)",
 "Namibia",
 "Nauru",
 "Nepal",
 "Nicaragua",
 "Niger",
 "Nigeria",
 "North Macedonia (formerly Macedonia)",
 "Pakistan",
 "Palestine",
 "Philippines",
 "Russia",
 "Rwanda",
 "São Tomé and Principe",
 "Senegal",
 "Serbia",
 "Sierra Leone",
 "Somalia",
 "South Africa",
 "South Sudan",
 "Sri Lanka",
 "St Lucia",
 "Sudan",
 "Suriname",
 "Syria",
 "Taiwan*",
 "Tajikistan",
 "Tanzania",
 "Thailand",
 "Timor-Leste",
 "Togo",
 "Trinidad and Tobago",
 "Tunisia",
 "Turkey",
 "Turkmenistan",
 "Uganda",
 "Ukraine",
 "Uzbekistan",
 "Vanuatu",
 "Venezuela",
 "Vietnam",
 "Yemen",
 "Zambia",
 "Zimbabwe"
];
export const ukEtaNationals = [
 "(a) for travel to the UK on or after 15 November 2023:",
 "Qatar",
 "(b) for travel to the UK on or after 22 February 2024:",
 "Bahrain",
 "Kuwait",
 "Oman",
 "United Arab Emirates",
 "Saudi Arabia",
 "(c) for travel to the UK on or after 8 January 2025:",
 "Antigua and Barbuda",
 "Argentina",
 "Australia",
 "Barbados",
 "Belize",
 "Brazil",
 "Brunei",
 "Canada",
 "Chile",
 "Costa Rica",
 "Grenada",
 "Guatemala",
 "Guyana",
 "Hong Kong Special Administrative Region",
 "Israel",
 "Japan",
 "Kiribati",
 "Macao Special Administrative Region",
 "Malaysia",
 "Maldives",
 "Marshall Islands",
 "Mauritius",
 "Mexico",
 "Federated States of Micronesia",
 "New Zealand",
 "Palau",
 "Panama",
 "Papua New Guinea",
 "Paraguay",
 "Peru",
 "St Kitts and Nevis",
 "St Vincent and the Grenadines",
 "Samoa",
 "Seychelles",
 "Singapore",
 "Solomon Islands",
 "South Korea",
 "Taiwan*",
 "The Bahamas",
 "Tonga",
 "Tuvalu",
 "United States",
 "Uruguay",
 "*Those who hold a passport issued by Taiwan that includes in it the number of the identification card issued by the competent authority in Taiwan.",
 "(d) travelling to the UK on or after 2 April 2025:",
 "Andorra",
 "Austria",
 "Belgium",
 "Bulgaria",
 "Croatia",
 "Cyprus",
 "Czechia",
 "Denmark",
 "Estonia",
 "Finland",
 "France",
 "Germany",
 "Greece",
 "Hungary",
 "Iceland",
 "Italy",
 "Latvia",
 "Liechtenstein",
 "Lithuania",
 "Luxembourg",
 "Malta",
 "Monaco",
 "Netherlands",
 "Norway",
 "Poland",
 "Portugal",
 "Romania",
 "San Marino",
 "Slovakia",
 "Slovenia",
 "Spain",
 "Sweden",
 "Switzerland",
 "Vatican City"
];
export const canadaVisa = [
 "Afghanistan",
 "Albania",
 "Algeria",
 "Angola",
 "Antigua and Barbuda (Some citizens of Antigua and Barbuda may be eligible for an electronic travel authorization [eTA] if they meet certain requirements.)",
 "Argentina (Some citizens of Argentina may be eligible for an eTA if they meet certain requirements.)",
 "Armenia",
 "Azerbaijan",
 "Bahrain",
 "Bangladesh",
 "Belarus",
 "Belize",
 "Benin",
 "Bhutan",
 "Bolivia",
 "Bosnia-Herzegovina",
 "Botswana",
 "Brazil (Some citizens of Brazil may be eligible for an eTA if they meet certain requirements.)",
 "Burkina Faso",
 "Burundi",
 "Cambodia",
 "Cameroon, Republic of",
 "Cabo Verde",
 "Central African Republic",
 "Chad",
 "China, People's Republic of",
 "Colombia",
 "Comoros",
 "Congo, Democratic Republic of",
 "Congo, Republic of",
 "Costa Rica, Republic of (Some citizens of Costa Rica may be eligible for an eTA if they meet certain requirements.)",
 "Cuba",
 "Djibouti",
 "Dominica",
 "Dominican Republic",
 "Ecuador",
 "Egypt",
 "El Salvador",
 "Equatorial Guinea",
 "Eritrea",
 "Eswatini",
 "Ethiopia",
 "Fiji",
 "Gabon",
 "Gambia",
 "Georgia",
 "Ghana",
 "Grenada",
 "Guatemala",
 "Guinea",
 "Guinea-Bissau",
 "Guyana",
 "Haiti",
 "Honduras",
 "India",
 "Indonesia (Some citizens of Indonesia may be eligible for an eTA if they meet certain requirements.)",
 "Iran",
 "Iraq",
 "Israel (Travellers must have a valid Israeli “Travel Document in Lieu of National Passport”.)",
 "Ivory Coast",
 "Jamaica",
 "Jordan",
 "Kazakhstan",
 "Kenya",
 "Kiribati",
 "Korea, North",
 "Kosovo",
 "Kuwait",
 "Kyrgyzstan",
 "Laos",
 "Lebanon",
 "Lesotho",
 "Liberia",
 "Libya",
 "Macao Special Administrative Region",
 "Madagascar",
 "Malawi",
 "Malaysia (Some citizens of Malaysia may be eligible for an eTA if they meet certain requirements.)",
 "Maldives Islands",
 "Mali",
 "Marshall Islands",
 "Mauritania",
 "Mauritius",
 "Mexico (Some citizens of Mexico may be eligible for an eTA if they meet certain requirements.)",
 "Micronesia, Fed. States",
 "Moldova",
 "Mongolia",
 "Montenegro",
 "Morocco (Some citizens of Morocco may be eligible for an eTA if they meet certain requirements.)",
 "Mozambique",
 "Myanmar",
 "Namibia",
 "Nauru",
 "Nepal",
 "Nicaragua",
 "Niger",
 "Nigeria",
 "North Macedonia",
 "Oman",
 "Pakistan",
 "Palau",
 "Palestine",
 "Panama (Some citizens of Panama may be eligible for an eTA if they meet certain requirements.)",
 "Paraguay",
 "Peru",
 "Philippines (Some citizens of the Philippines may be eligible for an eTA if they meet certain requirements.)",
 "Romania (holder of a non-electronic passport, such as a temporary passport)",
 "Russia",
 "Rwanda",
 "Sao Tomé e Principe",
 "Saudi Arabia, Kingdom of",
 "Senegal",
 "Serbia",
 "Seychelles (Some citizens of the Seychelles may be eligible for an eTA if they meet certain requirements.)",
 "Sierra Leone",
 "Somalia",
 "South Africa",
 "South Sudan",
 "Sri Lanka",
 "St. Kitts and Nevis (Some citizens of St. Kitts and Nevis may be eligible for an eTA if they meet certain requirements.)",
 "St. Lucia (Some citizens of St. Lucia may be eligible for an eTA if they meet certain requirements.)",
 "St. Vincent and the Grenadines (St. Vincent) (Some citizens of St. Vincent and the Grenadines may be eligible for an eTA if they meet certain requirements.)",
 "Sudan",
 "Suriname",
 "Syria",
 "Taiwan (Travellers must have a passport other than an ordinary passport issued by the Ministry of Foreign Affairs in Taiwan that includes the personal identification number.)",
 "Tajikistan",
 "Tanzania",
 "Thailand (Some citizens of Thailand may be eligible for an eTA if they meet certain requirements.)",
 "Timor-Leste",
 "Togo",
 "Tonga",
 "Trinidad and Tobago (Some citizens of Trinidad and Tobago may be eligible for an eTA if they meet certain requirements.)",
 "Tunisia",
 "Türkiye",
 "Turkmenistan",
 "Tuvalu",
 "Uganda",
 "Ukraine",
 "Uruguay (Some citizens of Uruguay may be eligible for an eTA if they meet certain requirements.)",
 "Uzbekistan",
 "Vanuatu",
 "Venezuela",
 "Vietnam",
 "Yemen",
 "Zambia",
 "Zimbabwe"
];
export const canadaEta = [
 "Andorra",
 "Australia",
 "Austria",
 "Bahamas",
 "Barbados",
 "Belgium",
 "British citizen",
 "British national overseas",
 "British overseas citizen (re-admissible to the United Kingdom)",
 "British overseas territory citizen with citizenship through birth, descent, naturalization or registration in one of the British overseas territories of",
 "Anguilla",
 "Bermuda",
 "British Virgin Islands",
 "Cayman Islands",
 "Falkland Islands (Malvinas)",
 "Gibraltar",
 "Montserrat",
 "Pitcairn Island",
 "Saint Helena",
 "Turks and Caicos Islands",
 "British subject with a right of abode in the United Kingdom",
 "Brunei Darussalam",
 "Bulgaria",
 "Chile",
 "Croatia",
 "Cyprus",
 "Czech Republic",
 "Denmark",
 "Estonia",
 "Finland",
 "France",
 "Germany",
 "Greece",
 "Hong Kong Special Administrative Region (SAR) of the People’s Republic of China (must have a passport issued by Hong Kong SAR)",
 "Hungary",
 "Iceland",
 "Ireland",
 "Israel (must have a national Israeli passport)",
 "Italy",
 "Japan",
 "Latvia",
 "Liechtenstein",
 "Lithuania",
 "Luxembourg",
 "Malta",
 "Monaco",
 "Netherlands",
 "New Zealand",
 "Norway",
 "Papua New Guinea",
 "Poland",
 "Portugal",
 "Qatar",
 "Republic of Korea",
 "Romania (electronic passport holders only)",
 "Samoa",
 "San Marino",
 "Singapore",
 "Slovakia",
 "Slovenia",
 "Solomon Islands",
 "Spain",
 "Sweden",
 "Switzerland",
 "Taiwan (must have an ordinary passport issued by the Ministry of Foreign Affairs in Taiwan that includes the personal identification number)",
 "United Arab Emirates",
 "Vatican City State (must have a passport or travel document issued by the Vatican)"
];
export const singaporeVisa = [
 "Afghanistan",
 "Algeria",
 "Armenia",
 "Azerbaijan",
 "Bangladesh",
 "Belarus",
 "Democratic People's Republic of Korea",
 "Egypt",
 "Georgia",
 "India",
 "Iran",
 "Iraq",
 "Jordan",
 "Kazakhstan",
 "Kosovo",
 "Kyrgyzstan",
 "Lebanon",
 "Libya",
 "Mali",
 "Moldova",
 "Morocco",
 "Nigeria",
 "Pakistan",
 "Russia",
 "Somalia",
 "South Sudan",
 "Sudan",
 "Syria",
 "Tajikistan",
 "Tunisia",
 "Turkmenistan",
 "Ukraine",
 "Uzbekistan",
 "Yemen"
];
export const saudiEvisa = [
 "North America",
 "Bahamas",
 "Barbados",
 "Canada",
 "Grenada",
 "Panama",
 "Saint Kitts and Nevis",
 "United States",
 "South America",
 "Guyana",
 "Europe",
 "Albania",
 "Andorra",
 "Austria",
 "Belgium",
 "Bulgaria",
 "Croatia",
 "Cyprus",
 "Czech Republic",
 "Denmark",
 "Estonia",
 "Finland",
 "France",
 "Georgia",
 "Germany",
 "Greece",
 "Netherlands",
 "Hungary",
 "Iceland",
 "Ireland",
 "Italy",
 "Kosovo",
 "Latvia",
 "Liechtenstein",
 "Lithuania",
 "Luxembourg",
 "Malta",
 "Monaco",
 "Montenegro",
 "Norway",
 "Poland",
 "Portugal",
 "Romania",
 "Russia",
 "San Marino",
 "Slovakia",
 "Slovenia",
 "Spain",
 "Sweden",
 "Switzerland",
 "Ukraine",
 "United Kingdom",
 "Asia",
 "Azerbaijan",
 "Brunei",
 "China (including Hong Kong and Macau)",
 "Japan",
 "Kazakhstan",
 "Kyrgyzstan",
 "Malaysia",
 "Maldives",
 "Singapore",
 "South Korea",
 "Tajikistan",
 "Thailand",
 "Turkey",
 "Uzbekistan",
 "Africa",
 "Mauritius",
 "Seychelles",
 "South Africa",
 "Oceania",
 "Australia",
 "New Zealand"
];
export const euAnnexLines = [
 "ANNEX I",
 "LIST OF THIRD COUNTRIES WHOSE NATIONALS ARE REQUIRED TO BE IN POSSESSION OF A VISA WHEN CROSSING THE EXTERNAL BORDERS OF THE MEMBER STATES",
 "1.   STATES",
 "Afghanistan",
 "Armenia",
 "Angola",
 "Azerbaijan",
 "Bangladesh",
 "Burkina Faso",
 "Bahrain",
 "Burundi",
 "Benin",
 "Bolivia",
 "Bhutan",
 "Botswana",
 "Belarus",
 "Belize",
 "Democratic Republic of the Congo",
 "Central African Republic",
 "Congo",
 "Côte d'Ivoire",
 "Cameroon",
 "China",
 "Cuba",
 "Cape Verde",
 "Djibouti",
 "Dominican Republic",
 "Algeria",
 "Ecuador",
 "Egypt",
 "Eritrea",
 "Eswatini",
 "Ethiopia",
 "Fiji",
 "Gabon",
 "Ghana",
 "The Gambia",
 "Guinea",
 "Equatorial Guinea",
 "Guinea-Bissau",
 "Guyana",
 "Haiti",
 "Indonesia",
 "India",
 "Iraq",
 "Iran",
 "Jamaica",
 "Jordan",
 "Kenya",
 "Kyrgyzstan",
 "Cambodia",
 "Comoros",
 "North Korea",
 "Kuwait",
 "Kazakhstan",
 "Laos",
 "Lebanon",
 "Sri Lanka",
 "Liberia",
 "Lesotho",
 "Libya",
 "Morocco",
 "Madagascar",
 "Mali",
 "Myanmar/Burma",
 "Mongolia",
 "Mauritania",
 "Maldives",
 "Malawi",
 "Mozambique",
 "Namibia",
 "Niger",
 "Nigeria",
 "Nepal",
 "Oman",
 "Papua New Guinea",
 "Philippines",
 "Pakistan",
 "Qatar",
 "Russia",
 "Rwanda",
 "Saudi Arabia",
 "Sudan",
 "Sierra Leone",
 "Senegal",
 "Somalia",
 "Suriname",
 "South Sudan",
 "São Tomé and Príncipe",
 "Syria",
 "Chad",
 "Togo",
 "Thailand",
 "Tajikistan",
 "Turkmenistan",
 "Tunisia",
 "Turkey",
 "Tanzania",
 "Uganda",
 "Uzbekistan",
 "▼M6",
 "Vanuatu",
 "▼B",
 "Vietnam",
 "Yemen",
 "South Africa",
 "Zambia",
 "Zimbabwe",
 "2.   ENTITIES AND TERRITORIAL AUTHORITIES THAT ARE NOT RECOGNISED AS STATES BY AT LEAST ONE MEMBER STATE",
 "▼M3 —————",
 "▼B",
 "—",
 "The Palestinian Authority",
 "ANNEX II",
 "LIST OF THIRD COUNTRIES WHOSE NATIONALS ARE EXEMPT FROM THE REQUIREMENT TO BE IN POSSESSION OF A VISA WHEN CROSSING THE EXTERNAL BORDERS OF THE MEMBER STATES FOR STAYS OF NO MORE THAN 90 DAYS IN ANY 180-DAY PERIOD",
 "1.   STATES",
 "former Yugoslav Republic of Macedonia (",
 "6",
 ")",
 "Andorra",
 "United Arab Emirates (",
 "7",
 ")",
 "Antigua and Barbuda",
 "Albania (6)",
 "Argentina",
 "Australia",
 "Bosnia and Herzegovina (6)",
 "Barbados",
 "Brunei",
 "Brazil",
 "Bahamas",
 "Canada",
 "Chile",
 "Colombia",
 "Costa Rica",
 "Dominica (7)",
 "Micronesia (7)",
 "Grenada (7)",
 "Georgia (",
 "8",
 ")",
 "Guatemala",
 "Honduras",
 "Israel",
 "Japan",
 "Kiribati (7)",
 "Saint Kitts and Nevis",
 "South Korea",
 "Saint Lucia (7)",
 "Monaco",
 "Moldova (",
 "9",
 ")",
 "Montenegro (",
 "10",
 ")",
 "Marshall Islands (",
 "11",
 ")",
 "Mauritius",
 "Mexico",
 "Malaysia",
 "Nicaragua",
 "Nauru (11)",
 "New Zealand",
 "Panama",
 "Peru (11)",
 "Palau (11)",
 "Paraguay",
 "▼M5",
 "Serbia (including holders of Serbian passports issued by the Serbian Coordination Directorate (in Serbian: Koordinaciona uprava",
 "(",
 "12",
 ")",
 "▼B",
 "Solomon Islands",
 "Seychelles",
 "Singapore",
 "San Marino",
 "El Salvador",
 "Timor-Leste (11)",
 "Tonga (11)",
 "Trinidad and Tobago",
 "Tuvalu (11)",
 "Ukraine (",
 "13",
 ")",
 "▼M1",
 "United Kingdom (excluding British nationals as referred to in Part 3)",
 "▼B",
 "United States",
 "Uruguay",
 "Holy See",
 "Saint Vincent and the Grenadines (11)",
 "Venezuela",
 "▼M6 —————",
 "▼B",
 "Samoa",
 "2.   SPECIAL ADMINISTRATIVE REGIONS OF THE PEOPLE'S REPUBLIC OF CHINA",
 "Hong Kong SAR (",
 "14",
 ")",
 "Macao SAR (",
 "15",
 ")",
 "3.",
 "►M1",
 "BRITISH NATIONALS WHO ARE NOT BRITISH CITIZENS ◄",
 "British nationals (Overseas)",
 "British overseas territories citizens (BOTC)",
 "►M1",
 "Those territories include Anguilla, Bermuda, British Antarctic Territory, British Indian Ocean Territory, British Virgin Islands, Cayman Islands, Falkland Islands, Gibraltar (",
 "16",
 "), Montserrat, Pitcairn, Saint Helena, Ascension and Tristan da Cunha, South Georgia and South Sandwich Islands and Turks and Caicos Islands. ◄",
 "British overseas citizens (BOC)",
 "British protected persons (BPP)",
 "British subjects (BS)",
 "4.   ENTITIES AND TERRITORIAL AUTHORITIES THAT ARE NOT RECOGNISED AS STATES BY AT LEAST ONE MEMBER STATE",
 "Taiwan (",
 "17",
 ")",
 "▼M3",
 "Kosovo (",
 "18",
 ")",
 "(",
 "19",
 ")",
 "(",
 "20",
 ")",
 "▼B",
 "ANNEX III"
];
export const euFootnoteLines = [
 "ANNEX IV",
 "CORRELATION TABLE",
 "Regulation (EC) No 539/2001",
 "This Regulation",
 "Article -1",
 "Article 1",
 "Article 1(1), first subparagraph",
 "Article 3(1)",
 "Article 1(1), second subparagraph",
 "Article 3(2)",
 "Article 1(2), first subparagraph",
 "Article 4(1)",
 "Article 1(2), second subparagraph, introductory wording",
 "Article 4(2), introductory wording",
 "Article 1(2), second subparagraph, first indent",
 "Article 4(2)(a)",
 "Article 1(2), second subparagraph, second indent",
 "Article 4(2)(b)",
 "Article 1(2), second subparagraph, third indent",
 "Article 4(2)(c)",
 "Article 1(3)",
 "Article 5",
 "Article 1(4)",
 "Article 7",
 "Article 1a(1) and (2)",
 "Article 8(1) and (2)",
 "Article 1a(2a)",
 "Article 8(3)",
 "Article 1a(2b)",
 "Article 8(4)",
 "Article 1a(3)",
 "Article 8(5)",
 "Article 1a(4)",
 "Article 8(6)",
 "Article 1a(5)",
 "Article 8(7)",
 "Article 1a(6)",
 "Article 8(8)",
 "Article 1b",
 "Article 9(1)",
 "Article 1c",
 "Article 9(2)",
 "Article 2",
 "Article 2",
 "Article 4",
 "Article 6",
 "Article 4a",
 "Article 11",
 "Article 4b(1) and (2)",
 "Article 10(1) and (2)",
 "Article 4b(2a)",
 "Article 10(3)",
 "Article 4b(3)",
 "Article 10(4)",
 "Article 4b(3a)",
 "Article 10(5)",
 "Article 4b(4)",
 "Article 10(6)",
 "Article 4b(5)",
 "Article 10(7)",
 "Article 4b(6)",
 "Article 10(8)",
 "Article 5",
 "Article 12",
 "Article 6",
 "Article 13",
 "Article 7",
 "Article 14",
 "Article 8",
 "Article 15",
 "Annex I",
 "Annex I",
 "Annex II",
 "Annex II",
 "—",
 "Annex III",
 "—",
 "Annex IV",
 "(",
 "*1",
 ") This designation is without prejudice to positions on status, and is in line with UNSCR 1244/1999 and the ICJ Opinion on the Kosovo declaration of independence.",
 "(",
 "1",
 ") Regulation (EC) No 810/2009 of the European Parliament and of the Council of 13 July 2009 establishing a Community Code on Visas (Visa Code) (OJ L 243, 15.9.2009, p. 1).",
 "(",
 "2",
 ") Council Decision 94/795/JHA of 30 November 1994 on a joint action adopted by the Council on the basis of Article K.3.2.b of the Treaty on European Union concerning travel facilities for school pupils from third countries resident in a Member State (OJ L 327, 19.12.1994, p. 1).",
 "(",
 "3",
 ") Regulation (EU) 2019/1896 of the European Parliament and of the Council of 13 November 2019 on the European Border and Coast Guard and repealing Regulations (EU) No 1052/2013 and (EU) 2016/1624 (OJ L 295, 14.11.2019, p. 1, ELI: http://data.europa.eu/eli/reg/2019/1896/oj).",
 "(",
 "4",
 ") Regulation (EU) 2021/2303 of the European Parliament and of the Council of 15 December 2021 on the European Union Agency for Asylum and repealing Regulation (EU) No 439/2010 (OJ L 468, 30.12.2021, p. 1, ELI: http://data.europa.eu/eli/reg/2021/2303/oj).",
 "(",
 "5",
 ") Regulation (EU) 2016/794 of the European Parliament and of the Council of 11 May 2016 on the European Union Agency for Law Enforcement Cooperation (Europol) and replacing and repealing Council Decisions 2009/371/JHA, 2009/934/JHA, 2009/935/JHA, 2009/936/JHA and 2009/968/JHA (OJ L 135, 24.5.2016, p. 53, ELI: http://data.europa.eu/eli/reg/2016/794/oj).",
 "(",
 "6",
 ") The exemption from the visa requirement shall only apply to holders of biometric passports.",
 "(",
 "7",
 ") The exemption from the visa requirement shall apply from the date of entry into force of an agreement on visa exemption to be concluded with the European Union.",
 "(",
 "8",
 ") The exemption from the visa requirement shall be limited to the holders of biometric passports issued by Georgia in line with standards of the International Civil Aviation Organisation (ICAO).",
 "(",
 "9",
 ") The exemption from the visa requirement shall be limited to the holders of biometric passports issued by Moldova in line with standards of the International Civil Aviation Organisation (ICAO).",
 "(",
 "10",
 ") The exemption from the visa requirement shall only apply to holders of biometric passports.",
 "(",
 "11",
 ") The exemption from the visa requirement shall apply from the date of entry into force of an agreement on visa exemption to be concluded with the European Union.",
 "(",
 "12",
 ") The exemption from the visa requirement shall only apply to holders of biometric passports issued in line with the standards of the International Civil Aviation Organization (ICAO).",
 "(",
 "13",
 ") The exemption from the visa requirement shall be limited to the holders of biometric passports issued by Ukraine in line with standards of the International Civil Aviation Organisation (ICAO).",
 "(",
 "14",
 ") The exemption from the visa requirement shall only apply to holders of a ‘Hong Kong Special Administrative Region’ passport.",
 "(",
 "15",
 ") The exemption from the visa requirement shall only apply to holders of a ‘Região Administrativa Especial de Macau’ passport.",
 "►M1",
 "(",
 "16",
 ") Gibraltar is a colony of the British Crown. There is a controversy between Spain and the United Kingdom concerning the sovereignty over Gibraltar, a territory for which a solution has to be reached in light of the relevant resolutions and decisions of the General Assembly of the United Nations. ◄",
 "(",
 "17",
 ") The exemption from the visa requirement shall only apply to holders of passports issued by Taiwan which include an identity card number.",
 "(",
 "18",
 ") This designation is without prejudice to positions on status, and is in line with UNSCR 1244/1999 and the ICJ Opinion on the Kosovo declaration of independence.",
 "(",
 "19",
 ") The exemption from the visa requirement shall only apply to holders of biometric passports issued by Kosovo in line with the standards of the International Civil Aviation Organisation (ICAO).",
 "(",
 "20",
 ") The exemption from the visa requirement shall apply from the date on which the European Travel Information and Authorisation System (ETIAS), established by Regulation (EU) 2018/1240 of the European Parliament and of the Council of 12 September 2018 establishing a European Travel Information and Authorisation System (ETIAS) and amending Regulations (EU) No 1077/2011, (EU) No 515/2014, (EU) 2016/399, (EU) 2016/1624 and (EU) 2017/2226 (OJ L 236, 19.9.2018, p. 1), starts operations or from 1 January 2024, whichever date comes first."
];
