// Phase 21 — the authoritative admin metric dictionary.
//
// Every number the /admin dashboard shows is defined HERE, once: what it
// counts, over what unit, against what denominator, in which time window,
// from which table or event, how to read it, and where it misleads. The
// dashboard reads its labels and its "how is this counted?" panels from this
// object (adminPage.ts serializes it into the page next to ADMIN_I18N), and
// ADMIN_METRICS.md at the repository root is generated from it by
// adminMetrics.test.ts — so the page, the doc and the SQL cannot quietly
// disagree about what a metric means.
//
// Vocabulary used by the definitions:
//   * session — one anonymous random id kept in the browser's sessionStorage
//     (app/src/telemetry/productDataClient.ts). It lives as long as one tab.
//     A new tab, another device or cleared site data is a new session. A
//     session is never a person.
//   * questionnaire action — a quiz_started, quiz_answer or
//     quiz_results_generated event.
//   * idle — a session with no event of any kind for STOP_IDLE_MINUTES.

export const STOP_IDLE_MINUTES = 30;

export interface Bilingual { ar: string; en: string }

export type MetricUnit =
  | 'sessions' | 'events' | 'percent' | 'milliseconds' | 'score' | 'countries'
  | 'cityLookups' | 'questions' | 'position' | 'reports' | 'ratings' | 'date';
export type MetricAggregation = 'count' | 'distinctSessions' | 'ratio' | 'mean' | 'distinctCount' | 'latest';
export type MetricWindow = 'eventTime' | 'sessionOverlap' | 'createdTime' | 'staticSnapshot' | 'cacheLifetime';
export type MetricTab = 'overview' | 'funnel' | 'quality' | 'countries' | 'discovery' | 'location' | 'reports' | 'technical' | 'content';

export interface MetricDefinition {
  id: string;
  tab: MetricTab;
  label: Bilingual;
  definition: Bilingual;
  unit: MetricUnit;
  numerator: Bilingual;
  /** null for a plain count: there is nothing it is divided by. */
  denominator: Bilingual | null;
  aggregation: MetricAggregation;
  window: MetricWindow;
  /** Technical provenance: the table and event names the SQL reads. */
  source: string;
  interpretation: Bilingual;
  limitation: Bilingual;
}

const SESSION_LIMIT: Bilingual = {
  en: 'A session is one browser tab, not a person: the same traveller on two tabs or two devices counts twice.',
  ar: 'الجلسة تبويب متصفح واحد وليست شخصًا: المسافر نفسه في تبويبين أو جهازين يُحتسب مرتين.',
};

export const ADMIN_METRICS: MetricDefinition[] = [
  // ------------------------------------------------------------ overview
  {
    id: 'overview.sessions', tab: 'overview',
    label: { en: 'Sessions', ar: 'الجلسات' },
    definition: { en: 'Anonymous sessions active at any point inside the selected range.', ar: 'الجلسات المجهولة التي كان لها نشاط في أي لحظة داخل النطاق المحدد.' },
    unit: 'sessions', aggregation: 'count', window: 'sessionOverlap', source: 'sessions',
    numerator: { en: 'Sessions whose first and last activity overlap the range and match the filters', ar: 'الجلسات التي يتقاطع أول وآخر نشاط لها مع النطاق وتطابق عوامل التصفية' },
    denominator: null,
    interpretation: { en: 'How much the product was used. Compare ranges of equal length.', ar: 'حجم استخدام المنتج. قارن بين نطاقات متساوية الطول.' },
    limitation: SESSION_LIMIT,
  },
  {
    id: 'overview.pageViews', tab: 'overview',
    label: { en: 'Page views', ar: 'مشاهدات الصفحات' },
    definition: { en: 'Screens shown: one page view per move to another page or language switch.', ar: 'الشاشات المعروضة: مشاهدة واحدة لكل انتقال إلى صفحة أخرى أو تبديل للغة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: page_view',
    numerator: { en: 'Page-view events in the range', ar: 'أحداث مشاهدة الصفحات ضمن النطاق' },
    denominator: null,
    interpretation: { en: 'Depth of browsing. Page views ÷ sessions ≈ screens per session.', ar: 'عمق التصفح. مشاهدات الصفحات ÷ الجلسات ≈ عدد الشاشات لكل جلسة.' },
    limitation: { en: 'Switching the site language re-counts the current screen.', ar: 'تبديل لغة الموقع يعيد احتساب الشاشة الحالية.' },
  },
  {
    id: 'overview.questionnaireSessions', tab: 'overview',
    label: { en: 'Questionnaire sessions', ar: 'جلسات الاستبيان' },
    definition: { en: 'Sessions that entered the questionnaire: picked a purpose, answered a question or reached results.', ar: 'الجلسات التي دخلت الاستبيان: اختارت غرضًا أو أجابت عن سؤال أو وصلت إلى النتائج.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_started, quiz_answer, quiz_results_generated',
    numerator: { en: 'Distinct sessions with any questionnaire action in the range', ar: 'الجلسات المميزة التي لديها أي إجراء استبيان ضمن النطاق' },
    denominator: null,
    interpretation: { en: 'The base every questionnaire rate on this dashboard is divided by.', ar: 'الأساس الذي تُقسم عليه كل معدلات الاستبيان في هذه اللوحة.' },
    limitation: { en: 'Opening the questionnaire from “Edit my preferences” skips the purpose picker; answering is what counts it then.', ar: 'فتح الاستبيان من «تعديل تفضيلاتي» يتجاوز اختيار الغرض؛ فيُحتسب عندها بأول إجابة.' },
  },
  {
    id: 'overview.completions', tab: 'overview',
    label: { en: 'Completed questionnaires', ar: 'الاستبيانات المكتملة' },
    definition: { en: 'Sessions that reached results at least once.', ar: 'الجلسات التي وصلت إلى النتائج مرة واحدة على الأقل.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_results_generated',
    numerator: { en: 'Distinct sessions that reached results in the range', ar: 'الجلسات المميزة التي وصلت إلى النتائج ضمن النطاق' },
    denominator: null,
    interpretation: { en: 'A session that completes twice (retake or edited preferences) is still one.', ar: 'الجلسة التي تُكمل مرتين (إعادة أو تعديل تفضيلات) تُحتسب مرة واحدة.' },
    limitation: { en: 'Includes completions that end on a destination page (“How well does it suit me?”) as well as on Results.', ar: 'يشمل الإكمال الذي ينتهي في صفحة وجهة («ما مدى ملاءمتها لي؟») وكذلك في صفحة النتائج.' },
  },
  {
    id: 'overview.completionRate', tab: 'overview',
    label: { en: 'Completion rate', ar: 'معدّل الإكمال' },
    definition: { en: 'Share of questionnaire sessions that reached results.', ar: 'نسبة جلسات الاستبيان التي وصلت إلى النتائج.' },
    unit: 'percent', aggregation: 'ratio', window: 'eventTime', source: 'events: quiz_started, quiz_answer, quiz_results_generated',
    numerator: { en: 'Completed questionnaires', ar: 'الاستبيانات المكتملة' },
    denominator: { en: 'Questionnaire sessions', ar: 'جلسات الاستبيان' },
    interpretation: { en: 'Higher is better. A drop points at a question or step where people leave — see the Funnel tab.', ar: 'كلما ارتفع كان أفضل. الانخفاض يشير إلى سؤال أو خطوة يغادر عندها الناس — راجع تبويب مسار الاستبيان.' },
    limitation: { en: 'Sessions still answering at the end of the range count as not completed.', ar: 'الجلسات التي لا تزال تُجيب عند نهاية النطاق تُحتسب غير مكتملة.' },
  },
  {
    id: 'overview.resultsViewed', tab: 'overview',
    label: { en: 'Results page views', ar: 'مشاهدات صفحة النتائج' },
    definition: { en: 'Times the Results screen was shown.', ar: 'عدد مرات عرض شاشة النتائج.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: page_view on /results',
    numerator: { en: 'Page views of the Results screen', ar: 'مشاهدات شاشة النتائج' },
    denominator: null,
    interpretation: { en: 'Returns to Results (back navigation, language switch) count again.', ar: 'العودة إلى النتائج (الرجوع أو تبديل اللغة) تُحتسب مرة أخرى.' },
    limitation: { en: 'A questionnaire opened from a destination page ends on that page, not on Results.', ar: 'الاستبيان المفتوح من صفحة وجهة ينتهي في تلك الصفحة وليس في النتائج.' },
  },
  {
    id: 'overview.ratings', tab: 'overview',
    label: { en: 'Ratings', ar: 'التقييمات' },
    definition: { en: 'Ratings submitted: results ratings and destination ratings together.', ar: 'التقييمات المرسلة: تقييمات النتائج وتقييمات الوجهات معًا.' },
    unit: 'ratings', aggregation: 'count', window: 'createdTime', source: 'ratings',
    numerator: { en: 'Rating rows created in the range', ar: 'صفوف التقييم المنشأة ضمن النطاق' },
    denominator: null,
    interpretation: { en: 'Volume behind the average rating: few ratings mean a fragile average.', ar: 'الحجم الذي يستند إليه متوسط التقييم: قلة التقييمات تعني متوسطًا هشًّا.' },
    limitation: { en: 'Only travellers who chose to rate are counted — a self-selected group.', ar: 'تُحتسب فقط تقييمات من اختار التقييم — عيّنة اختارت نفسها.' },
  },
  {
    id: 'overview.averageRating', tab: 'overview',
    label: { en: 'Average rating', ar: 'متوسط التقييم' },
    definition: { en: 'Mean overall score of all ratings in the range, on a 1–5 scale.', ar: 'متوسط الدرجة الكلية لكل التقييمات ضمن النطاق، على مقياس من 1 إلى 5.' },
    unit: 'score', aggregation: 'mean', window: 'createdTime', source: 'ratings.overall_score',
    numerator: { en: 'Sum of overall scores', ar: 'مجموع الدرجات الكلية' },
    denominator: { en: 'Number of ratings', ar: 'عدد التقييمات' },
    interpretation: { en: 'Read it next to the rating count and the distribution on the Recommendation quality tab.', ar: 'اقرأه مع عدد التقييمات والتوزيع في تبويب جودة التوصيات.' },
    limitation: { en: 'Mixes results ratings and destination ratings, which answer different questions.', ar: 'يمزج تقييمات النتائج وتقييمات الوجهات، وهما يجيبان عن سؤالين مختلفين.' },
  },
  {
    id: 'overview.reports', tab: 'overview',
    label: { en: 'Reports', ar: 'البلاغات' },
    definition: { en: 'Reports and feedback messages travellers sent.', ar: 'البلاغات ورسائل الملاحظات التي أرسلها المسافرون.' },
    unit: 'reports', aggregation: 'count', window: 'createdTime', source: 'feedback',
    numerator: { en: 'Feedback rows created in the range', ar: 'صفوف الملاحظات المنشأة ضمن النطاق' },
    denominator: null,
    interpretation: { en: 'Work waiting in the Reports tab; open it to triage.', ar: 'عمل ينتظر في تبويب البلاغات؛ افتحه للفرز.' },
    limitation: { en: 'Counts reports whose anonymous session still exists. After 90 days a report is detached from its session, and only the Reports tab still lists it.', ar: 'يعدّ البلاغات التي لا تزال جلستها المجهولة موجودة. بعد 90 يومًا يُفصل البلاغ عن جلسته، ولا يعرضه إلا تبويب البلاغات.' },
  },

  // -------------------------------------------------------------- funnel
  {
    id: 'funnel.averageDistinctQuestions', tab: 'funnel',
    label: { en: 'Average questions answered', ar: 'متوسط الأسئلة المُجابة' },
    definition: { en: 'Mean number of DIFFERENT questions a session answered.', ar: 'متوسط عدد الأسئلة المختلفة التي أجابت عنها الجلسة.' },
    unit: 'questions', aggregation: 'mean', window: 'eventTime', source: 'events: quiz_answer.questionId',
    numerator: { en: 'Sum over sessions of distinct questions answered', ar: 'مجموع الأسئلة المختلفة المُجابة عبر الجلسات' },
    denominator: { en: 'Sessions that answered at least one question', ar: 'الجلسات التي أجابت عن سؤال واحد على الأقل' },
    interpretation: { en: 'How deep people go. Early results are offered after 5 answers; the full length depends on the purpose and on whether a location was shared.', ar: 'إلى أي عمق يصل الناس. تُعرض النتائج المبكرة بعد 5 إجابات؛ ويعتمد الطول الكامل على الغرض وعلى مشاركة الموقع.' },
    limitation: { en: 'Changing an answer does not add a question; answering the same question in two purposes adds two.', ar: 'تغيير الإجابة لا يضيف سؤالًا؛ والإجابة عن السؤال نفسه في غرضين تضيف سؤالين.' },
  },
  {
    id: 'funnel.outcome.finished', tab: 'funnel',
    label: { en: 'Finished with results', ar: 'انتهت بالنتائج' },
    definition: { en: 'Questionnaire sessions whose latest questionnaire action was reaching results.', ar: 'جلسات الاستبيان التي كان آخر إجراء فيها هو الوصول إلى النتائج.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_answer, quiz_results_generated',
    numerator: { en: 'Sessions whose last completion is not followed by another answer', ar: 'الجلسات التي لا تتبع آخرَ إكمال فيها أيُّ إجابة' },
    denominator: { en: 'Questionnaire sessions (the four outcomes add up to it)', ar: 'جلسات الاستبيان (النتائج الأربع مجموعها يساويها)' },
    interpretation: { en: 'The healthy outcome.', ar: 'النتيجة السليمة.' },
    limitation: SESSION_LIMIT,
  },
  {
    id: 'funnel.outcome.stopped', tab: 'funnel',
    label: { en: 'Stopped before results', ar: 'توقفت قبل النتائج' },
    definition: { en: `Sessions whose latest questionnaire action was an answer, with no results after it and no activity for ${STOP_IDLE_MINUTES} minutes.`, ar: `الجلسات التي كان آخر إجراء استبيان فيها إجابةً، دون نتائج بعدها ودون أي نشاط لمدة ${STOP_IDLE_MINUTES} دقيقة.` },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_answer, quiz_results_generated; sessions.last_seen_at',
    numerator: { en: 'Idle sessions whose last answer has no later completion', ar: 'الجلسات الخاملة التي لا يلي آخرَ إجابة فيها إكمال' },
    denominator: { en: 'Questionnaire sessions', ar: 'جلسات الاستبيان' },
    interpretation: { en: 'The drop-off. The question table shows which question each of these sessions answered last.', ar: 'حالات الانسحاب. جدول الأسئلة يبيّن آخر سؤال أجابت عنه كل جلسة منها.' },
    limitation: { en: 'A session that completed earlier and then left a later retake unfinished counts here, because its latest attempt stopped.', ar: 'الجلسة التي أكملت سابقًا ثم تركت إعادة لاحقة دون إكمال تُحتسب هنا، لأن محاولتها الأخيرة توقفت.' },
  },
  {
    id: 'funnel.outcome.inProgress', tab: 'funnel',
    label: { en: 'Still answering', ar: 'لا تزال تُجيب' },
    definition: { en: `Like “Stopped before results”, but the session was active in the last ${STOP_IDLE_MINUTES} minutes — it may still finish.`, ar: `مثل «توقفت قبل النتائج»، لكن الجلسة كانت نشطة في آخر ${STOP_IDLE_MINUTES} دقيقة — قد تُكمل بعد.` },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_answer, quiz_results_generated; sessions.last_seen_at',
    numerator: { en: 'Recently active sessions whose last answer has no later completion', ar: 'الجلسات النشطة مؤخرًا التي لا يلي آخرَ إجابة فيها إكمال' },
    denominator: { en: 'Questionnaire sessions', ar: 'جلسات الاستبيان' },
    interpretation: { en: 'Kept apart so a live session is never reported as a drop-off.', ar: 'تُفصل حتى لا تُحتسب جلسة حية كحالة انسحاب.' },
    limitation: { en: `Measured against the time the dashboard loaded; it moves as time passes.`, ar: 'يُقاس نسبةً إلى وقت تحميل اللوحة؛ ويتغير بمرور الوقت.' },
  },
  {
    id: 'funnel.outcome.neverAnswered', tab: 'funnel',
    label: { en: 'Picked a purpose, answered nothing', ar: 'اختارت غرضًا ولم تُجب' },
    definition: { en: 'Sessions that picked a purpose but never answered a question or reached results.', ar: 'الجلسات التي اختارت غرضًا لكنها لم تُجب عن أي سؤال ولم تصل إلى النتائج.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_started, quiz_answer, quiz_results_generated',
    numerator: { en: 'Sessions that picked a purpose with no answer and no completion', ar: 'الجلسات التي اختارت غرضًا دون أي إجابة أو إكمال' },
    denominator: { en: 'Questionnaire sessions', ar: 'جلسات الاستبيان' },
    interpretation: { en: 'People who left at the first question itself.', ar: 'من غادروا عند السؤال الأول نفسه.' },
    limitation: { en: 'Includes sessions still looking at the first question.', ar: 'يشمل جلسات لا تزال تنظر إلى السؤال الأول.' },
  },
  {
    id: 'funnel.completedMoreThanOnce', tab: 'funnel',
    label: { en: 'Completed more than once', ar: 'أكملت أكثر من مرة' },
    definition: { en: 'Sessions that reached results two or more times — a retake or “Edit my preferences”.', ar: 'الجلسات التي وصلت إلى النتائج مرتين أو أكثر — إعادة أو «تعديل تفضيلاتي».' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_results_generated',
    numerator: { en: 'Sessions with 2+ completions', ar: 'الجلسات التي لديها إكمالان أو أكثر' },
    denominator: { en: 'Completed questionnaires', ar: 'الاستبيانات المكتملة' },
    interpretation: { en: 'Engagement with personalization, or dissatisfaction with a first set of results.', ar: 'تفاعل مع التخصيص، أو عدم رضا عن أول مجموعة نتائج.' },
    limitation: SESSION_LIMIT,
  },
  {
    id: 'funnel.restarted', tab: 'funnel',
    label: { en: 'Restarted', ar: 'بدأت من جديد' },
    definition: { en: 'Sessions that picked a purpose two or more times.', ar: 'الجلسات التي اختارت غرضًا مرتين أو أكثر.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_started',
    numerator: { en: 'Sessions that picked a purpose twice or more', ar: 'الجلسات التي اختارت غرضًا مرتين أو أكثر' },
    denominator: { en: 'Questionnaire sessions', ar: 'جلسات الاستبيان' },
    interpretation: { en: 'Going back to the purpose picker mid-questionnaire or after results.', ar: 'العودة إلى اختيار الغرض أثناء الاستبيان أو بعد النتائج.' },
    limitation: { en: 'Choosing the same purpose again counts as a restart.', ar: 'اختيار الغرض نفسه مرة أخرى يُحتسب بداية جديدة.' },
  },
  {
    id: 'funnel.changedPurpose', tab: 'funnel',
    label: { en: 'Changed purpose', ar: 'غيّرت الغرض' },
    definition: { en: 'Sessions that started two or more DIFFERENT purposes.', ar: 'الجلسات التي بدأت غرضين مختلفين أو أكثر.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_started.purpose',
    numerator: { en: 'Sessions with 2+ distinct started purposes', ar: 'الجلسات التي بدأت غرضين مختلفين أو أكثر' },
    denominator: { en: 'Questionnaire sessions', ar: 'جلسات الاستبيان' },
    interpretation: { en: 'A high value can mean the purpose names are unclear.', ar: 'ارتفاعه قد يعني أن أسماء الأغراض غير واضحة.' },
    limitation: { en: 'Cannot tell exploring several purposes from correcting a mis-click.', ar: 'لا يميّز بين استكشاف عدة أغراض وتصحيح نقرة خاطئة.' },
  },
  {
    id: 'funnel.checkpoint', tab: 'funnel',
    label: { en: 'Checkpoint after 5 answers', ar: 'نقطة التوقف بعد 5 إجابات' },
    definition: { en: 'What sessions chose when offered early results after the 5th answer.', ar: 'ما اختارته الجلسات عند عرض النتائج المبكرة بعد الإجابة الخامسة.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_checkpoint_choice.choice',
    numerator: { en: 'Sessions that made each choice', ar: 'الجلسات التي اتخذت كل خيار' },
    denominator: { en: 'Sessions that made any checkpoint choice', ar: 'الجلسات التي اتخذت أي خيار عند نقطة التوقف' },
    interpretation: { en: 'Many early exits suggest the remaining questions feel long.', ar: 'كثرة الخروج المبكر تشير إلى أن الأسئلة المتبقية تبدو طويلة.' },
    limitation: { en: 'Sessions that left at the checkpoint without choosing are not counted here; they appear as stopped after their 5th answer.', ar: 'الجلسات التي غادرت عند نقطة التوقف دون اختيار لا تُحتسب هنا؛ تظهر كمتوقفة بعد إجابتها الخامسة.' },
  },
  {
    id: 'funnel.question.sessions', tab: 'funnel',
    label: { en: 'Sessions that answered', ar: 'جلسات أجابت' },
    definition: { en: 'Distinct sessions that answered this question at least once.', ar: 'الجلسات المميزة التي أجابت عن هذا السؤال مرة واحدة على الأقل.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_answer.questionId',
    numerator: { en: 'Distinct sessions with an answer to this question', ar: 'الجلسات المميزة التي لديها إجابة عن هذا السؤال' },
    denominator: null,
    interpretation: { en: 'The questionnaire is adaptive: a question nobody reached may simply not be asked on common paths.', ar: 'الاستبيان متكيّف: السؤال الذي لم يصله أحد قد لا يُطرح أصلًا في المسارات الشائعة.' },
    limitation: { en: 'Location-dependent questions (distance and land borders) are only asked when a location is shared.', ar: 'الأسئلة المعتمدة على الموقع (المسافة والحدود البرية) لا تُطرح إلا عند مشاركة الموقع.' },
  },
  {
    id: 'funnel.question.answers', tab: 'funnel',
    label: { en: 'Answer events', ar: 'أحداث الإجابة' },
    definition: { en: 'Every time this question was answered, including changed answers and retakes.', ar: 'كل مرة أُجيب فيها عن هذا السؤال، بما في ذلك تغيير الإجابة وإعادة الاستبيان.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: quiz_answer.questionId',
    numerator: { en: 'Answer events for this question', ar: 'أحداث الإجابة عن هذا السؤال' },
    denominator: null,
    interpretation: { en: 'Answer events well above sessions means people revisit this question.', ar: 'زيادة أحداث الإجابة كثيرًا عن الجلسات تعني أن الناس يعودون إلى هذا السؤال.' },
    limitation: { en: 'Cannot tell a changed answer from a full retake.', ar: 'لا يميّز بين تغيير إجابة وإعادة الاستبيان بالكامل.' },
  },
  {
    id: 'funnel.question.averagePosition', tab: 'funnel',
    label: { en: 'Average position', ar: 'متوسط الموضع' },
    definition: { en: 'Where in the adaptive sequence this question was asked (1 = first), averaged, with the earliest–latest range.', ar: 'موضع هذا السؤال في التسلسل المتكيّف (1 = الأول)، كمتوسط مع المدى من الأبكر إلى الأخير.' },
    unit: 'position', aggregation: 'mean', window: 'eventTime', source: 'events: quiz_answer.questionNumber',
    numerator: { en: 'Sum of positions', ar: 'مجموع المواضع' },
    denominator: { en: 'Answer events for this question', ar: 'أحداث الإجابة لهذا السؤال' },
    interpretation: { en: 'A wide range means the adaptive order moves this question around.', ar: 'اتساع المدى يعني أن الترتيب المتكيّف ينقل هذا السؤال بين المواضع.' },
    limitation: { en: 'Position is where it was answered; a question reached but not answered has no position.', ar: 'الموضع هو حيث أُجيب عنه؛ السؤال الذي عُرض ولم يُجب عنه ليس له موضع.' },
  },
  {
    id: 'funnel.question.completedAfter', tab: 'funnel',
    label: { en: 'Went on to results', ar: 'وصلت إلى النتائج بعده' },
    definition: { en: 'Sessions that answered this question and reached results afterwards.', ar: 'الجلسات التي أجابت عن هذا السؤال ثم وصلت إلى النتائج بعده.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_answer, quiz_results_generated',
    numerator: { en: 'Sessions with a completion later than an answer to this question', ar: 'الجلسات التي لديها إكمال لاحق لإجابة عن هذا السؤال' },
    denominator: { en: 'Sessions that answered', ar: 'جلسات أجابت' },
    interpretation: { en: 'Continuation all the way to results from this question.', ar: 'الاستمرار من هذا السؤال حتى النتائج.' },
    limitation: SESSION_LIMIT,
  },
  {
    id: 'funnel.question.stoppedHere', tab: 'funnel',
    label: { en: 'Stopped after this question', ar: 'توقفت بعد هذا السؤال' },
    definition: { en: 'Stopped sessions (see “Stopped before results”) whose LAST answer was this question.', ar: 'الجلسات المتوقفة (راجع «توقفت قبل النتائج») التي كانت آخر إجابة فيها عن هذا السؤال.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_answer, quiz_results_generated; sessions.last_seen_at',
    numerator: { en: 'Stopped sessions whose last answer is this question', ar: 'الجلسات المتوقفة التي آخر إجابة فيها لهذا السؤال' },
    denominator: null,
    interpretation: { en: 'The person left on the NEXT screen — the next question, the 5-answer checkpoint, or the final step before results.', ar: 'غادر الشخص في الشاشة التالية — السؤال التالي، أو نقطة التوقف بعد 5 إجابات، أو الخطوة الأخيرة قبل النتائج.' },
    limitation: { en: 'Questions are not logged when shown, only when answered, so the exact screen left is not recorded.', ar: 'لا يُسجَّل السؤال عند عرضه بل عند الإجابة عنه فقط، لذا لا تُسجَّل الشاشة التي غادرها الشخص بدقة.' },
  },
  {
    id: 'funnel.question.dropOff', tab: 'funnel',
    label: { en: 'Drop-off after', ar: 'الانسحاب بعده' },
    definition: { en: 'Share of the sessions that answered this question which then stopped.', ar: 'نسبة الجلسات التي أجابت عن هذا السؤال ثم توقفت.' },
    unit: 'percent', aggregation: 'ratio', window: 'eventTime', source: 'events: quiz_answer, quiz_results_generated; sessions.last_seen_at',
    numerator: { en: 'Stopped after this question', ar: 'توقفت بعد هذا السؤال' },
    denominator: { en: 'Sessions that answered', ar: 'جلسات أجابت' },
    interpretation: { en: 'Compare questions within one purpose; the highest value marks the weakest step.', ar: 'قارن بين أسئلة الغرض الواحد؛ أعلى قيمة تحدد أضعف خطوة.' },
    limitation: { en: 'Small counts swing widely — read it with the session count.', ar: 'الأعداد الصغيرة تتذبذب كثيرًا — اقرأه مع عدد الجلسات.' },
  },
  {
    id: 'funnel.position.sessions', tab: 'funnel',
    label: { en: 'Sessions reaching each position', ar: 'الجلسات التي بلغت كل موضع' },
    definition: { en: 'Distinct sessions that answered a question at each position, whatever the question was.', ar: 'الجلسات المميزة التي أجابت عن سؤال في كل موضع، أيًّا كان السؤال.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: quiz_answer.questionNumber',
    numerator: { en: 'Distinct sessions with an answer at this position', ar: 'الجلسات المميزة التي لديها إجابة في هذا الموضع' },
    denominator: null,
    interpretation: { en: 'The classic funnel shape: how many get to question 1, 2, 3 …', ar: 'شكل القمع التقليدي: كم يصل إلى السؤال 1 و2 و3 …' },
    limitation: { en: 'Mixes purposes, whose questionnaires have different lengths.', ar: 'يمزج الأغراض، واستبياناتها مختلفة الطول.' },
  },
  {
    id: 'funnel.purpose.completionRate', tab: 'funnel',
    label: { en: 'Completion by purpose', ar: 'الإكمال حسب الغرض' },
    definition: { en: 'Per purpose: sessions that reached results ÷ sessions that answered in that purpose.', ar: 'لكل غرض: الجلسات التي وصلت إلى النتائج ÷ الجلسات التي أجابت في ذلك الغرض.' },
    unit: 'percent', aggregation: 'ratio', window: 'eventTime', source: 'events: quiz_started, quiz_answer, quiz_results_generated (.purpose)',
    numerator: { en: 'Sessions with a completion in this purpose', ar: 'الجلسات التي أكملت في هذا الغرض' },
    denominator: { en: 'Sessions that answered or completed in this purpose', ar: 'الجلسات التي أجابت أو أكملت في هذا الغرض' },
    interpretation: { en: 'Which purpose loses people. “Picked” counts sessions that chose the purpose on the picker.', ar: 'أي غرض يفقد الناس. «اختيار» يعدّ الجلسات التي اختارت الغرض من شاشة الأغراض.' },
    limitation: { en: 'A session that tried two purposes counts in both.', ar: 'الجلسة التي جرّبت غرضين تُحتسب في كليهما.' },
  },

  // ------------------------------------------------------------- quality
  {
    id: 'quality.distribution', tab: 'quality',
    label: { en: 'Ratings by score', ar: 'التقييمات حسب الدرجة' },
    definition: { en: 'How many ratings gave each score from 1 to 5.', ar: 'عدد التقييمات لكل درجة من 1 إلى 5.' },
    unit: 'ratings', aggregation: 'count', window: 'createdTime', source: 'ratings.overall_score',
    numerator: { en: 'Ratings with each score', ar: 'التقييمات بكل درجة' },
    denominator: null,
    interpretation: { en: 'Two peaks (1 and 5) mean the average hides a split.', ar: 'وجود قمتين (1 و5) يعني أن المتوسط يخفي انقسامًا.' },
    limitation: { en: 'Self-selected: only travellers who chose to rate.', ar: 'عيّنة اختارت نفسها: فقط من اختار التقييم.' },
  },
  {
    id: 'quality.countryAverage', tab: 'quality',
    label: { en: 'Destination rating by country', ar: 'تقييم الوجهة حسب الدولة' },
    definition: { en: 'Mean destination-page rating per country, lowest first.', ar: 'متوسط تقييم صفحة الوجهة لكل دولة، الأقل أولًا.' },
    unit: 'score', aggregation: 'mean', window: 'createdTime', source: 'ratings (kind = destination)',
    numerator: { en: 'Sum of destination ratings for the country', ar: 'مجموع تقييمات الوجهة للدولة' },
    denominator: { en: 'Destination ratings for the country', ar: 'تقييمات الوجهة للدولة' },
    interpretation: { en: 'Countries whose pages disappoint; check their content first.', ar: 'الدول التي تخيّب صفحاتها التوقعات؛ راجع محتواها أولًا.' },
    limitation: { en: 'One or two ratings make an unreliable average — read the count.', ar: 'تقييم أو تقييمان يعطيان متوسطًا غير موثوق — اقرأ العدد.' },
  },
  {
    id: 'quality.pathAverage', tab: 'quality',
    label: { en: 'Results rating by questionnaire path', ar: 'تقييم النتائج حسب مسار الاستبيان' },
    definition: { en: 'Results ratings grouped by the purpose and the number of answers in the rating session.', ar: 'تقييمات النتائج مجمّعة حسب الغرض وعدد الإجابات في جلسة التقييم.' },
    unit: 'score', aggregation: 'mean', window: 'createdTime', source: 'ratings (kind = results); events: quiz_started, quiz_answer',
    numerator: { en: 'Sum of results ratings on the path', ar: 'مجموع تقييمات النتائج في المسار' },
    denominator: { en: 'Results ratings on the path', ar: 'تقييمات النتائج في المسار' },
    interpretation: { en: 'Whether short questionnaires produce worse-rated results.', ar: 'هل تنتج الاستبيانات القصيرة نتائج أقل تقييمًا.' },
    limitation: { en: 'Uses the session’s first purpose and all its answers, even across retakes.', ar: 'يستخدم أول غرض في الجلسة وكل إجاباتها، حتى عبر الإعادات.' },
  },

  // ----------------------------------------------------------- countries
  {
    id: 'countries.everRecommended', tab: 'countries',
    label: { en: 'Countries ever recommended', ar: 'الدول التي أُوصي بها ولو مرة' },
    definition: { en: 'Distinct countries that appeared in at least one generated top 5.', ar: 'الدول المميزة التي ظهرت في قائمة أفضل 5 مولَّدة واحدة على الأقل.' },
    unit: 'countries', aggregation: 'distinctCount', window: 'eventTime', source: 'events: quiz_results_generated.results[]',
    numerator: { en: 'Distinct country codes in generated top-5 lists', ar: 'رموز الدول المميزة في قوائم أفضل 5 المولَّدة' },
    denominator: { en: '194 destinations in the catalog', ar: '194 وجهة في الكتالوج' },
    interpretation: { en: 'Breadth of recommendations; a small number means the same few countries win.', ar: 'اتساع التوصيات؛ الرقم الصغير يعني أن الدول نفسها تفوز دائمًا.' },
    limitation: { en: 'Only the top 5 are logged; places 6 and below are not visible here.', ar: 'تُسجَّل أفضل 5 فقط؛ المراتب من 6 فما دون لا تظهر هنا.' },
  },
  {
    id: 'countries.appearances', tab: 'countries',
    label: { en: 'Top-5 appearances', ar: 'مرات الظهور ضمن أفضل 5' },
    definition: { en: 'How many generated top-5 lists included the country.', ar: 'عدد قوائم أفضل 5 المولَّدة التي تضمنت الدولة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: quiz_results_generated.results[]',
    numerator: { en: 'Top-5 lists containing the country', ar: 'قوائم أفضل 5 التي تحتوي الدولة' },
    denominator: null,
    interpretation: { en: 'Least-recommended lists only countries that appeared at least once.', ar: 'قائمة الأقل توصية تضم فقط الدول التي ظهرت مرة واحدة على الأقل.' },
    limitation: { en: 'A session that completes twice contributes two lists.', ar: 'الجلسة التي تُكمل مرتين تضيف قائمتين.' },
  },
  {
    id: 'countries.opens', tab: 'countries',
    label: { en: 'Destination opens', ar: 'فتح صفحات الوجهات' },
    definition: { en: 'Destination pages opened by clicking a destination card.', ar: 'صفحات الوجهات المفتوحة بالنقر على بطاقة وجهة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: destination_opened',
    numerator: { en: 'Destination-card clicks that opened a page', ar: 'نقرات بطاقات الوجهات التي فتحت صفحة' },
    denominator: null,
    interpretation: { en: 'Where attention goes. “Source” says which screen the card was on.', ar: 'أين يتجه الاهتمام. «المصدر» يبيّن الشاشة التي كانت عليها البطاقة.' },
    limitation: { en: 'A page reached by typing or sharing its address is not counted.', ar: 'الصفحة التي يُوصل إليها بكتابة عنوانها أو مشاركته لا تُحتسب.' },
  },
  {
    id: 'countries.surpriseOpened', tab: 'countries',
    label: { en: 'Surprise Me results opened', ar: 'نتائج فاجئني بوجهة المفتوحة' },
    definition: { en: 'Destination opens that came from the Surprise Me wheel.', ar: 'مرات فتح الوجهات القادمة من عجلة فاجئني بوجهة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: destination_opened (source = surprise)',
    numerator: { en: 'Destination opens whose source is Surprise Me', ar: 'مرات فتح الوجهات التي مصدرها فاجئني بوجهة' },
    denominator: null,
    interpretation: { en: 'Compare with Surprise spins on the Discovery tab.', ar: 'قارنه بمرات تدوير فاجئني في تبويب الاستكشاف.' },
    limitation: { en: 'Same card-click limitation as destination opens.', ar: 'القيد نفسه الخاص بالنقر على البطاقة كما في فتح الوجهات.' },
  },
  {
    id: 'countries.surpriseLandings', tab: 'countries',
    label: { en: 'Surprise Me landings', ar: 'مرات استقرار فاجئني' },
    definition: { en: 'Countries the Surprise Me wheel landed on.', ar: 'الدول التي استقرت عليها عجلة فاجئني بوجهة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: surprise_result',
    numerator: { en: 'Times the wheel stopped on a country', ar: 'مرات توقف العجلة على دولة' },
    denominator: null,
    interpretation: { en: 'The wheel is random among the filtered candidates; heavy repeats point at narrow filters.', ar: 'العجلة عشوائية بين المرشحين بعد التصفية؛ كثرة التكرار تشير إلى تصفية ضيقة.' },
    limitation: { en: 'Counts landings, not whether the traveller liked the result.', ar: 'يعدّ مرات الاستقرار، لا رضا المسافر عن النتيجة.' },
  },
  {
    id: 'countries.reports', tab: 'countries',
    label: { en: 'Reports per country', ar: 'البلاغات لكل دولة' },
    definition: { en: 'Reports filed from a specific country page.', ar: 'البلاغات المقدَّمة من صفحة دولة محددة.' },
    unit: 'reports', aggregation: 'count', window: 'createdTime', source: 'feedback.country_code',
    numerator: { en: 'Feedback rows with this country code', ar: 'صفوف الملاحظات بهذا الرمز' },
    denominator: null,
    interpretation: { en: 'Open the Reports tab and search the country code to read them.', ar: 'افتح تبويب البلاغات وابحث برمز الدولة لقراءتها.' },
    limitation: { en: 'Reports sent from other pages carry no country.', ar: 'البلاغات المرسلة من صفحات أخرى لا تحمل دولة.' },
  },

  // ----------------------------------------------------------- discovery
  {
    id: 'discovery.searchInteractions', tab: 'discovery',
    label: { en: 'Search box uses', ar: 'استخدامات مربع البحث' },
    definition: { en: 'Times the Explore search box was left (focus moved away), with or without text.', ar: 'عدد مرات مغادرة مربع البحث في استكشف (انتقال التركيز)، بنص أو بدونه.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: explore_search',
    numerator: { en: 'Times the search box was left', ar: 'مرات مغادرة مربع البحث' },
    denominator: null,
    interpretation: { en: 'Interest in finding a named country.', ar: 'الاهتمام بالبحث عن دولة بالاسم.' },
    limitation: { en: 'The search text itself is never recorded — only whether there was any and its length.', ar: 'نص البحث نفسه لا يُسجَّل أبدًا — فقط وجوده وطوله.' },
  },
  {
    id: 'discovery.searchWithText', tab: 'discovery',
    label: { en: 'Searches with text', ar: 'عمليات بحث بنص' },
    definition: { en: 'Search box uses that left text in the box.', ar: 'استخدامات مربع البحث التي تُرك فيها نص.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: explore_search (used = true)',
    numerator: { en: 'Times the search box was left with text in it', ar: 'مرات مغادرة مربع البحث وفيه نص' },
    denominator: { en: 'Search box uses', ar: 'استخدامات مربع البحث' },
    interpretation: { en: 'Real searches, as opposed to clicking in and out.', ar: 'عمليات بحث فعلية، لا مجرد النقر داخل المربع وخارجه.' },
    limitation: { en: 'One search typed then refined counts once per time the box is left.', ar: 'البحث المكتوب ثم المعدَّل يُحتسب مرة لكل مغادرة للمربع.' },
  },
  {
    id: 'discovery.filterChanges', tab: 'discovery',
    label: { en: 'Filter and sort changes', ar: 'تغييرات التصفية والترتيب' },
    definition: { en: 'Changes to an Explore filter or the sort, by which control and which value.', ar: 'تغييرات عوامل التصفية أو الترتيب في استكشف، حسب العنصر والقيمة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: explore_filter_changed',
    numerator: { en: 'Changes to a filter or the sort', ar: 'تغييرات عوامل التصفية أو الترتيب' },
    denominator: null,
    interpretation: { en: 'Which ways of narrowing the catalog people actually use.', ar: 'طرق تضييق الكتالوج التي يستخدمها الناس فعلًا.' },
    limitation: { en: '“All …” means the control was set back to no filter.', ar: '«الكل …» تعني إعادة العنصر إلى عدم التصفية.' },
  },
  {
    id: 'discovery.filterResets', tab: 'discovery',
    label: { en: 'Filter resets', ar: 'إعادة ضبط التصفية' },
    definition: { en: 'Clicks on the Explore “reset filters” control.', ar: 'النقرات على زر «إعادة ضبط عوامل التصفية» في استكشف.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: explore_filters_reset',
    numerator: { en: 'Clicks on reset filters', ar: 'نقرات إعادة ضبط التصفية' },
    denominator: null,
    interpretation: { en: 'Frequent resets can mean filters lead to empty or unhelpful lists.', ar: 'كثرة إعادة الضبط قد تعني أن التصفية تنتهي بقوائم فارغة أو غير مفيدة.' },
    limitation: { en: 'Does not record which filters were active before the reset.', ar: 'لا يسجّل عوامل التصفية التي كانت مفعّلة قبل إعادة الضبط.' },
  },
  {
    id: 'discovery.surpriseSpins', tab: 'discovery',
    label: { en: 'Surprise spins', ar: 'مرات تدوير فاجئني' },
    definition: { en: 'Times the Surprise Me wheel was spun.', ar: 'عدد مرات تدوير عجلة فاجئني بوجهة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: surprise_spin',
    numerator: { en: 'Wheel spins', ar: 'مرات تدوير العجلة' },
    denominator: null,
    interpretation: { en: 'Spins ÷ sessions that spun ≈ spins per curious visitor.', ar: 'مرات التدوير ÷ الجلسات التي دوّرت ≈ عدد التدويرات لكل زائر فضولي.' },
    limitation: SESSION_LIMIT,
  },
  {
    id: 'discovery.surpriseSessions', tab: 'discovery',
    label: { en: 'Sessions that spun', ar: 'جلسات استخدمت فاجئني' },
    definition: { en: 'Distinct sessions that spun the Surprise Me wheel at least once.', ar: 'الجلسات المميزة التي دوّرت عجلة فاجئني بوجهة مرة واحدة على الأقل.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: surprise_spin',
    numerator: { en: 'Distinct sessions with at least one spin', ar: 'الجلسات المميزة التي لديها تدوير واحد على الأقل' },
    denominator: null,
    interpretation: { en: 'Reach of the Surprise Me feature.', ar: 'مدى وصول ميزة فاجئني بوجهة.' },
    limitation: SESSION_LIMIT,
  },

  // ------------------------------------------------------------ location
  {
    id: 'location.asked', tab: 'location',
    label: { en: 'Sessions that requested location', ar: 'جلسات طلبت الموقع' },
    definition: { en: 'Distinct sessions where the browser location request ran at least once.', ar: 'الجلسات المميزة التي نُفّذ فيها طلب الموقع من المتصفح مرة واحدة على الأقل.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: location_request_outcome',
    numerator: { en: 'Distinct sessions with a completed location request', ar: 'الجلسات المميزة التي لديها طلب موقع مكتمل' },
    denominator: null,
    interpretation: { en: 'How many travellers tried the location feature.', ar: 'عدد المسافرين الذين جرّبوا ميزة الموقع.' },
    limitation: { en: 'No coordinate is ever stored — only whether the request worked and how long it took.', ar: 'لا يُخزَّن أي إحداثي أبدًا — فقط هل نجح الطلب وكم استغرق.' },
  },
  {
    id: 'location.granted', tab: 'location',
    label: { en: 'Sessions that got a location', ar: 'جلسات حصلت على الموقع' },
    definition: { en: 'Distinct sessions where at least one location request succeeded.', ar: 'الجلسات المميزة التي نجح فيها طلب موقع واحد على الأقل.' },
    unit: 'sessions', aggregation: 'distinctSessions', window: 'eventTime', source: 'events: location_request_outcome (outcome = ok)',
    numerator: { en: 'Distinct sessions with a successful request', ar: 'الجلسات المميزة التي لديها طلب ناجح' },
    denominator: null,
    interpretation: { en: 'Travellers who can use the distance sorts and the nearby question.', ar: 'المسافرون الذين يمكنهم استخدام ترتيب المسافة وسؤال القرب.' },
    limitation: SESSION_LIMIT,
  },
  {
    id: 'location.grantRate', tab: 'location',
    label: { en: 'Location success rate', ar: 'معدّل نجاح الموقع' },
    definition: { en: 'Share of sessions that requested a location and got one.', ar: 'نسبة الجلسات التي طلبت الموقع وحصلت عليه.' },
    unit: 'percent', aggregation: 'ratio', window: 'eventTime', source: 'events: location_request_outcome',
    numerator: { en: 'Sessions that got a location', ar: 'جلسات حصلت على الموقع' },
    denominator: { en: 'Sessions that requested location', ar: 'جلسات طلبت الموقع' },
    interpretation: { en: 'A fall points at denials or timeouts — see the outcome tables.', ar: 'الانخفاض يشير إلى رفض أو انتهاء مهلة — راجع جداول النتائج.' },
    limitation: { en: 'A session that failed and later succeeded counts as a success.', ar: 'الجلسة التي فشلت ثم نجحت لاحقًا تُحتسب ناجحة.' },
  },
  {
    id: 'location.statusChanges', tab: 'location',
    label: { en: 'Location state changes', ar: 'تغيّرات حالة الموقع' },
    definition: { en: 'Each change of the site’s location state (asking, granted, denied …), as events and as distinct sessions.', ar: 'كل تغيّر في حالة الموقع داخل الموقع (جارٍ الطلب، مسموح، مرفوض …)، كأحداث وكجلسات مميزة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: location_permission.outcome',
    numerator: { en: 'State changes per state; and distinct sessions per state', ar: 'تغيّرات الحالة لكل حالة؛ والجلسات المميزة لكل حالة' },
    denominator: null,
    interpretation: { en: '“Asking” counts requests started; the other states count how they ended.', ar: '«جارٍ الطلب» يعدّ الطلبات التي بدأت؛ والحالات الأخرى تعدّ كيف انتهت.' },
    limitation: { en: 'One session can pass through several states, so sessions per state do not add up to a total.', ar: 'قد تمر الجلسة الواحدة بعدة حالات، لذا لا يجمع عدد الجلسات لكل حالة إلى إجمالي.' },
  },
  {
    id: 'location.requests', tab: 'location',
    label: { en: 'Location requests', ar: 'طلبات الموقع' },
    definition: { en: 'Completed location requests by result, with the mean time to that result.', ar: 'طلبات الموقع المكتملة حسب النتيجة، مع متوسط الوقت حتى النتيجة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: location_request_outcome (.outcome, .totalMs)',
    numerator: { en: 'Completed requests per result', ar: 'الطلبات المكتملة لكل نتيجة' },
    denominator: null,
    interpretation: { en: 'Long average times on success mean the second, high-accuracy stage was often needed.', ar: 'طول متوسط الوقت عند النجاح يعني أن المرحلة الثانية عالية الدقة كانت مطلوبة كثيرًا.' },
    limitation: { en: 'Time is measured in the browser, in milliseconds; a mean is pulled up by a few slow devices.', ar: 'يُقاس الوقت في المتصفح بالمللي ثانية؛ والمتوسط يرتفع بسبب أجهزة بطيئة قليلة.' },
  },
  {
    id: 'location.stageAttempts', tab: 'location',
    label: { en: 'Request stages', ar: 'مراحل الطلب' },
    definition: { en: 'Individual attempts inside location requests: stage 1 coarse and cached, stage 2 high accuracy.', ar: 'المحاولات الفردية داخل طلبات الموقع: المرحلة 1 تقريبية ومخزَّنة، والمرحلة 2 عالية الدقة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: location_request_outcome.stages[]',
    numerator: { en: 'Stage attempts per result and accuracy mode', ar: 'محاولات المراحل لكل نتيجة ونمط دقة' },
    denominator: null,
    interpretation: { en: 'High-accuracy attempts appear only after stage 1 timed out or was unavailable.', ar: 'محاولات الدقة العالية تظهر فقط بعد انتهاء مهلة المرحلة 1 أو تعذرها.' },
    limitation: { en: 'Counts attempts, not sessions.', ar: 'يعدّ المحاولات لا الجلسات.' },
  },
  {
    id: 'location.edgeSessions', tab: 'location',
    label: { en: 'Sessions by coarse country', ar: 'الجلسات حسب الدولة التقريبية' },
    definition: { en: 'Sessions by the country Cloudflare attaches to the request at its edge.', ar: 'الجلسات حسب الدولة التي تُلحقها شبكة Cloudflare بالطلب عند الحافة.' },
    unit: 'sessions', aggregation: 'count', window: 'sessionOverlap', source: 'sessions.edge_country',
    numerator: { en: 'Sessions per edge country', ar: 'الجلسات لكل دولة حافة' },
    denominator: null,
    interpretation: { en: 'Where the audience connects from, at country level only.', ar: 'من أين يتصل الجمهور، على مستوى الدولة فقط.' },
    limitation: { en: 'A VPN or roaming shows the network’s country, not the traveller’s. Never finer than a country.', ar: 'الشبكة الافتراضية أو التجوال يُظهران دولة الشبكة لا المسافر. ولا شيء أدق من الدولة.' },
  },

  // ----------------------------------------------------------- technical
  {
    id: 'technical.samples', tab: 'technical',
    label: { en: 'Performance samples', ar: 'عيّنات الأداء' },
    definition: { en: 'Full page loads that reported timing — one per load, not per screen change.', ar: 'تحميلات الصفحة الكاملة التي أبلغت عن التوقيت — واحدة لكل تحميل، لا لكل تغيّر شاشة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: page_performance',
    numerator: { en: 'Page loads that reported timing', ar: 'تحميلات الصفحة التي أبلغت عن التوقيت' },
    denominator: null,
    interpretation: { en: 'The number of loads the timing averages are based on.', ar: 'عدد التحميلات التي تستند إليها متوسطات التوقيت.' },
    limitation: { en: 'Moving between screens inside the site is not a new load and adds no sample.', ar: 'التنقل بين الشاشات داخل الموقع ليس تحميلًا جديدًا ولا يضيف عيّنة.' },
  },
  {
    id: 'technical.ttfb', tab: 'technical',
    label: { en: 'Average time to first byte', ar: 'متوسط الوقت حتى أول بايت' },
    definition: { en: 'Mean time from navigation start until the first byte of the page arrived.', ar: 'متوسط الوقت من بدء التنقل حتى وصول أول بايت من الصفحة.' },
    unit: 'milliseconds', aggregation: 'mean', window: 'eventTime', source: 'events: page_performance.ttfbMs',
    numerator: { en: 'Sum of time to first byte', ar: 'مجموع الوقت حتى أول بايت' },
    denominator: { en: 'Performance samples', ar: 'عيّنات الأداء' },
    interpretation: { en: 'Network and hosting speed as travellers experience it.', ar: 'سرعة الشبكة والاستضافة كما يختبرها المسافرون.' },
    limitation: { en: 'A mean, not a percentile: a few slow connections pull it up.', ar: 'متوسط لا مئين: قلة من الاتصالات البطيئة ترفعه.' },
  },
  {
    id: 'technical.domReady', tab: 'technical',
    label: { en: 'Average document ready', ar: 'متوسط جاهزية المستند' },
    definition: { en: 'Mean time from navigation start until the document was parsed and deferred scripts ran.', ar: 'متوسط الوقت من بدء التنقل حتى تحليل المستند وتشغيل السكربتات المؤجلة.' },
    unit: 'milliseconds', aggregation: 'mean', window: 'eventTime', source: 'events: page_performance.domReadyMs',
    numerator: { en: 'Sum of document-ready times', ar: 'مجموع أوقات جاهزية المستند' },
    denominator: { en: 'Performance samples', ar: 'عيّنات الأداء' },
    interpretation: { en: 'Roughly when the page becomes usable.', ar: 'تقريبًا متى تصبح الصفحة قابلة للاستخدام.' },
    limitation: { en: 'A mean, not a percentile.', ar: 'متوسط لا مئين.' },
  },
  {
    id: 'technical.load', tab: 'technical',
    label: { en: 'Average full load', ar: 'متوسط التحميل الكامل' },
    definition: { en: 'Mean time from navigation start until the load event finished (images included).', ar: 'متوسط الوقت من بدء التنقل حتى انتهاء حدث التحميل (بما فيه الصور).' },
    unit: 'milliseconds', aggregation: 'mean', window: 'eventTime', source: 'events: page_performance.loadMs',
    numerator: { en: 'Sum of load times', ar: 'مجموع أوقات التحميل' },
    denominator: { en: 'Performance samples', ar: 'عيّنات الأداء' },
    interpretation: { en: 'Upper bound of the first-visit wait.', ar: 'الحد الأعلى لانتظار الزيارة الأولى.' },
    limitation: { en: 'A tab opened in the background finishes loading late and inflates it.', ar: 'التبويب المفتوح في الخلفية يُنهي التحميل متأخرًا فيضخّمه.' },
  },
  {
    id: 'technical.errors', tab: 'technical',
    label: { en: 'Frontend errors', ar: 'أخطاء الواجهة' },
    definition: { en: 'Uncaught script errors and unhandled promise rejections, by error name and file.', ar: 'أخطاء السكربت غير الملتقطة ورفض الوعود غير المعالج، حسب اسم الخطأ والملف.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: client_error (.kind, .script)',
    numerator: { en: 'Error events per error name and file', ar: 'أحداث الخطأ لكل اسم خطأ وملف' },
    denominator: null,
    interpretation: { en: 'A new name or a jump after a deploy is worth investigating.', ar: 'ظهور اسم جديد أو قفزة بعد النشر يستحق التحقيق.' },
    limitation: { en: 'No message and no stack are kept (they can carry user content); browser extensions can add noise.', ar: 'لا تُحفظ الرسالة ولا تتبّع المكدس (قد يحملان محتوى المستخدم)؛ وإضافات المتصفح قد تضيف ضجيجًا.' },
  },
  {
    id: 'technical.sessionsBy', tab: 'technical',
    label: { en: 'Sessions by browser, device and language', ar: 'الجلسات حسب المتصفح والجهاز واللغة' },
    definition: { en: 'Sessions grouped by browser family, screen-width class and the site language last used.', ar: 'الجلسات مجمّعة حسب عائلة المتصفح وفئة عرض الشاشة وآخر لغة استُخدمت في الموقع.' },
    unit: 'sessions', aggregation: 'count', window: 'sessionOverlap', source: 'sessions (browser_family, device_class, locale)',
    numerator: { en: 'Sessions per value', ar: 'الجلسات لكل قيمة' },
    denominator: null,
    interpretation: { en: 'Which browsers and screen sizes to test first.', ar: 'أي المتصفحات وأحجام الشاشات تُختبر أولًا.' },
    limitation: { en: 'Device class is screen width (under 640 px mobile, under 1024 px tablet), not the hardware.', ar: 'فئة الجهاز هي عرض الشاشة (أقل من 640 بكسل جوال، وأقل من 1024 لوحي)، لا نوع الجهاز.' },
  },
  {
    id: 'technical.themeViews', tab: 'technical',
    label: { en: 'Page views by theme', ar: 'مشاهدات الصفحات حسب المظهر' },
    definition: { en: 'Page views grouped by the light or dark theme active when the page was shown.', ar: 'مشاهدات الصفحات مجمّعة حسب المظهر الفاتح أو الداكن النشط عند عرض الصفحة.' },
    unit: 'events', aggregation: 'count', window: 'eventTime', source: 'events: page_view.theme',
    numerator: { en: 'Page views per theme', ar: 'مشاهدات الصفحات لكل مظهر' },
    denominator: null,
    interpretation: { en: 'How much each theme matters for visual QA.', ar: 'أهمية كل مظهر في الفحص البصري.' },
    limitation: { en: 'Counts page views, not people; a theme switch mid-visit splits one visit.', ar: 'يعدّ المشاهدات لا الأشخاص؛ وتبديل المظهر أثناء الزيارة يقسمها.' },
  },

  // ------------------------------------------------------------- content
  {
    id: 'content.lookedUp', tab: 'content',
    label: { en: 'City lookups', ar: 'عمليات البحث عن المدن' },
    definition: { en: 'City descriptions looked up and cached, one per city and language.', ar: 'أوصاف المدن التي بُحث عنها وخُزّنت، واحد لكل مدينة ولغة.' },
    unit: 'cityLookups', aggregation: 'count', window: 'cacheLifetime', source: 'city_descriptions',
    numerator: { en: 'Rows in the description cache', ar: 'الصفوف في مخزن الأوصاف' },
    denominator: null,
    interpretation: { en: 'Grows as travellers open destination pages; not affected by the date filter.', ar: 'يزداد كلما فتح المسافرون صفحات الوجهات؛ ولا يتأثر بمرشح التاريخ.' },
    limitation: { en: 'A city nobody opened yet has no row, so this is not a coverage of the whole catalog.', ar: 'المدينة التي لم يفتحها أحد بعد ليس لها صف، لذا هذا ليس تغطية للكتالوج كله.' },
  },
  {
    id: 'content.verified', tab: 'content',
    label: { en: 'With a verified description', ar: 'بوصف موثّق' },
    definition: { en: 'Lookups that found an article whose own coordinates match the city.', ar: 'عمليات البحث التي وجدت مقالًا تتطابق إحداثياته الخاصة مع المدينة.' },
    unit: 'cityLookups', aggregation: 'ratio', window: 'cacheLifetime', source: 'city_descriptions (status = ok)',
    numerator: { en: 'Lookups with status ok', ar: 'عمليات البحث بحالة موثّق' },
    denominator: { en: 'City lookups', ar: 'عمليات البحث عن المدن' },
    interpretation: { en: 'The share of opened cities that show a description.', ar: 'نسبة المدن المفتوحة التي تعرض وصفًا.' },
    limitation: { en: 'The coordinates are the article’s published ones, compared on the server; nothing about the traveller.', ar: 'الإحداثيات هي المنشورة للمقال وتُقارن على الخادم؛ لا شيء يخص المسافر.' },
  },
  {
    id: 'content.countriesSeen', tab: 'content',
    label: { en: 'Countries with a lookup', ar: 'دول لها عمليات بحث' },
    definition: { en: 'Distinct countries that have at least one city lookup.', ar: 'الدول المميزة التي لها عملية بحث واحدة على الأقل عن مدينة.' },
    unit: 'countries', aggregation: 'distinctCount', window: 'cacheLifetime', source: 'city_descriptions.country_code',
    numerator: { en: 'Distinct country codes in the cache', ar: 'رموز الدول المميزة في المخزن' },
    denominator: { en: '194 destinations in the catalog', ar: '194 وجهة في الكتالوج' },
    interpretation: { en: 'How many destination pages have been opened at least once since the cache started.', ar: 'عدد صفحات الوجهات التي فُتحت مرة واحدة على الأقل منذ بدء التخزين.' },
    limitation: { en: 'An expired entry is looked up again but keeps its row, so this only grows.', ar: 'الإدخال المنتهي يُبحث عنه من جديد لكنه يحتفظ بصفه، لذا هذا الرقم يزداد فقط.' },
  },
  {
    id: 'intelligence.countriesCovered', tab: 'content',
    label: { en: 'Countries in the dataset', ar: 'الدول في مجموعة البيانات' },
    definition: { en: 'Countries in the bundled Country Intelligence dataset that powers “Best suited for” and Purpose Suitability.', ar: 'الدول في مجموعة بيانات معلومات الدول المضمّنة التي تشغّل «الأنسب لـ» وملاءمة الغرض.' },
    unit: 'countries', aggregation: 'distinctCount', window: 'staticSnapshot', source: 'worker/src/generated/countryIntelligenceDetail.json',
    numerator: { en: 'Distinct country codes in the snapshot', ar: 'رموز الدول المميزة في اللقطة' },
    denominator: { en: '194 destinations in the catalog', ar: '194 وجهة في الكتالوج' },
    interpretation: { en: 'Should equal 194. Anything lower means the pipeline dropped countries.', ar: 'يجب أن يساوي 194. أي رقم أقل يعني أن خط البيانات أسقط دولًا.' },
    limitation: { en: 'A static file shipped with the server code; the date filter does not apply.', ar: 'ملف ثابت يُشحن مع شيفرة الخادم؛ ولا ينطبق عليه مرشح التاريخ.' },
  },
  {
    id: 'intelligence.generatedAt', tab: 'content',
    label: { en: 'Dataset generated', ar: 'تاريخ توليد البيانات' },
    definition: { en: 'When the Country Intelligence pipeline last produced the dataset, and how many days ago that was.', ar: 'متى أنتج خط معلومات الدول مجموعة البيانات آخر مرة، وكم يومًا مضى على ذلك.' },
    unit: 'date', aggregation: 'latest', window: 'staticSnapshot', source: 'countryIntelligenceDetail.json generatedAt',
    numerator: { en: 'The generation time recorded in the file', ar: 'وقت التوليد المسجّل في الملف' },
    denominator: null,
    interpretation: { en: 'Freshness. The underlying indicators are yearly; months old is expected, years old is not.', ar: 'الحداثة. المؤشرات الأساسية سنوية؛ عمر أشهر متوقع، وعمر سنوات غير متوقع.' },
    limitation: { en: 'The date of the build, not of each source’s latest release.', ar: 'تاريخ البناء، لا تاريخ آخر إصدار لكل مصدر.' },
  },
  {
    id: 'intelligence.sufficient', tab: 'content',
    label: { en: 'Countries with enough data', ar: 'دول ببيانات كافية' },
    definition: { en: 'Per purpose: countries with enough indicator coverage to show a suitability score.', ar: 'لكل غرض: الدول التي تملك تغطية مؤشرات كافية لعرض درجة ملاءمة.' },
    unit: 'countries', aggregation: 'count', window: 'staticSnapshot', source: 'countryIntelligenceDetail.json insufficientData',
    numerator: { en: 'Countries not marked insufficient', ar: 'الدول غير الموسومة بعدم الكفاية' },
    denominator: { en: 'Countries in the dataset', ar: 'الدول في مجموعة البيانات' },
    interpretation: { en: 'Below 60% coverage no score is computed; those countries show “not enough data” instead of a guessed score.', ar: 'دون تغطية 60% لا تُحسب درجة؛ وتعرض تلك الدول «بيانات غير كافية» بدل درجة مخمَّنة.' },
    limitation: { en: 'Enough data is a methodology threshold, not a quality grade of the country.', ar: 'كفاية البيانات عتبة منهجية، لا تقدير لجودة الدولة.' },
  },
  {
    id: 'intelligence.averageCoverage', tab: 'content',
    label: { en: 'Average indicator coverage', ar: 'متوسط تغطية المؤشرات' },
    definition: { en: 'Per purpose: mean share of the purpose’s factors actually observed for a country.', ar: 'لكل غرض: متوسط نسبة عوامل الغرض المرصودة فعلًا للدولة.' },
    unit: 'percent', aggregation: 'mean', window: 'staticSnapshot', source: 'countryIntelligenceDetail.json coverage',
    numerator: { en: 'Sum of per-country coverage', ar: 'مجموع التغطية لكل دولة' },
    denominator: { en: 'Countries in the dataset', ar: 'الدول في مجموعة البيانات' },
    interpretation: { en: 'Higher means fewer gaps behind the scores.', ar: 'الارتفاع يعني فجوات أقل خلف الدرجات.' },
    limitation: { en: 'Coverage is measured, not imputed: a missing indicator stays missing.', ar: 'التغطية مقيسة لا مقدّرة: المؤشر المفقود يبقى مفقودًا.' },
  },
  {
    id: 'intelligence.highConfidence', tab: 'content',
    label: { en: 'High-confidence countries', ar: 'دول بثقة عالية' },
    definition: { en: 'Per purpose: countries rated high confidence — coverage of at least 90% and an average data age of 3 years or less.', ar: 'لكل غرض: الدول ذات الثقة العالية — تغطية 90% على الأقل ومتوسط عمر بيانات 3 سنوات أو أقل.' },
    unit: 'countries', aggregation: 'count', window: 'staticSnapshot', source: 'countryIntelligenceDetail.json confidence',
    numerator: { en: 'Countries with confidence high', ar: 'الدول بثقة عالية' },
    denominator: { en: 'Countries in the dataset', ar: 'الدول في مجموعة البيانات' },
    interpretation: { en: 'Where the suitability scores are most trustworthy.', ar: 'حيث تكون درجات الملاءمة أجدر بالثقة.' },
    limitation: { en: 'Confidence describes the data behind a score, not how good the country is.', ar: 'الثقة تصف البيانات خلف الدرجة، لا مدى جودة الدولة.' },
  },

  // ------------------------------------------------------------- reports
  {
    id: 'reports.matching', tab: 'reports',
    label: { en: 'Matching reports', ar: 'البلاغات المطابقة' },
    definition: { en: 'Reports that match the filters above and the search, status, type and screenshot choices.', ar: 'البلاغات المطابقة لعوامل التصفية أعلاه ولاختيارات البحث والحالة والنوع ولقطة الشاشة.' },
    unit: 'reports', aggregation: 'count', window: 'createdTime', source: 'feedback',
    numerator: { en: 'Matching feedback rows', ar: 'صفوف الملاحظات المطابقة' },
    denominator: null,
    interpretation: { en: 'Status and type counts below describe the same matching set.', ar: 'أعداد الحالات والأنواع أدناه تصف المجموعة المطابقة نفسها.' },
    limitation: { en: 'The search looks inside the message, the reference and the country code only.', ar: 'البحث يشمل الرسالة والمرجع ورمز الدولة فقط.' },
  },
  {
    id: 'reports.withScreenshot', tab: 'reports',
    label: { en: 'With a screenshot', ar: 'مع لقطة شاشة' },
    definition: { en: 'Matching reports that arrived with a screenshot attached.', ar: 'البلاغات المطابقة التي وصلت مع لقطة شاشة مرفقة.' },
    unit: 'reports', aggregation: 'count', window: 'createdTime', source: 'feedback.screenshot_key',
    numerator: { en: 'Matching reports with a stored screenshot', ar: 'البلاغات المطابقة التي لها لقطة مخزّنة' },
    denominator: { en: 'Matching reports', ar: 'البلاغات المطابقة' },
    interpretation: { en: 'Visual bugs are usually easier to act on with a screenshot.', ar: 'الأخطاء البصرية أسهل معالجة عادةً مع لقطة شاشة.' },
    limitation: { en: 'The dashboard shows only that a screenshot exists; the image stays in private storage.', ar: 'تُظهر اللوحة وجود اللقطة فقط؛ وتبقى الصورة في تخزين خاص.' },
  },
  {
    id: 'reports.ratingComments', tab: 'reports',
    label: { en: 'Rating comments', ar: 'تعليقات التقييم' },
    definition: { en: 'Ratings that came with a written comment, newest first.', ar: 'التقييمات المصحوبة بتعليق مكتوب، الأحدث أولًا.' },
    unit: 'ratings', aggregation: 'count', window: 'createdTime', source: 'ratings.comment',
    numerator: { en: 'Ratings with a non-empty comment', ar: 'التقييمات ذات التعليق غير الفارغ' },
    denominator: null,
    interpretation: { en: 'The travellers’ own words next to their score.', ar: 'كلمات المسافرين أنفسهم بجانب درجاتهم.' },
    limitation: { en: 'Shown as written; never mined, classified or translated.', ar: 'تُعرض كما كُتبت؛ دون تنقيب أو تصنيف أو ترجمة.' },
  },
];

export const ADMIN_METRIC_IDS = new Set(ADMIN_METRICS.map((metric) => metric.id));
