import type { Lang } from '../data/types';

export const FAVORITES_COPY = {
  ar: {
    nav: 'المفضلة',
    toggle: 'المفضلة',
    toggleFor: (name: string) => `المفضلة: ${name}`,
    added: (name: string) => `أُضيفت ${name} إلى المفضلة.`,
    removed: (name: string) => `أُزيلت ${name} من المفضلة.`,
    notRemembered: 'لا يمكن حفظ المفضلة على هذا الجهاز الآن؛ ستبقى حتى تغلق الصفحة.',
    title: 'المفضلة',
    lead: 'الوجهات التي حفظتها على هذا الجهاز. لا حساب ولا مزامنة: تبقى في متصفحك فقط.',
    count: (n: number) => (n === 1 ? 'وجهة واحدة محفوظة' : n === 2 ? 'وجهتان محفوظتان' : `${n} وجهات محفوظة`),
    emptyTitle: 'لا توجد وجهات محفوظة بعد',
    emptyBody: 'احفظ أي وجهة بزر «المفضلة» في صفحتها أو في الاستكشاف لتجدها هنا وتقارن بينها.',
    emptyCta: 'استكشف الوجهات',
    open: 'افتح الوجهة',
    remove: 'إزالة',
    removeFor: (name: string) => `إزالة ${name} من المفضلة`,
    selectForCompare: (name: string) => `اختر ${name} للمقارنة`,
    compareSelected: (n: number) => `قارن المختار (${n})`,
    compareHint: 'اختر وجهتين أو ثلاثًا للمقارنة.',
    compareLimit: 'يمكن مقارنة ثلاث وجهات كحد أقصى.',
  },
  en: {
    nav: 'Favorites',
    toggle: 'Favorite',
    toggleFor: (name: string) => `Favorite: ${name}`,
    added: (name: string) => `${name} added to favorites.`,
    removed: (name: string) => `${name} removed from favorites.`,
    notRemembered: 'Favorites cannot be saved on this device right now; they will last until you close the page.',
    title: 'Favorites',
    lead: 'Destinations you saved on this device. No account and no sync: they stay in your browser only.',
    count: (n: number) => (n === 1 ? '1 saved destination' : `${n} saved destinations`),
    emptyTitle: 'No saved destinations yet',
    emptyBody: 'Save any destination with the Favorite button on its page or in Explore to find it here and compare.',
    emptyCta: 'Explore destinations',
    open: 'Open destination',
    remove: 'Remove',
    removeFor: (name: string) => `Remove ${name} from favorites`,
    selectForCompare: (name: string) => `Select ${name} to compare`,
    compareSelected: (n: number) => `Compare selected (${n})`,
    compareHint: 'Select two or three destinations to compare.',
    compareLimit: 'You can compare up to three destinations.',
  },
} satisfies Record<Lang, Record<string, unknown>>;
