// Downloads the exact web fonts the site already used from Google Fonts and
// stores them in src/assets/fonts/, then generates src/styles/fonts.css with
// local @font-face rules.
//
// Why: index.html previously linked fonts.googleapis.com at runtime. That sent
// every visitor's IP address and User-Agent to a third party on page load, and
// it forced the Content-Security-Policy to allow two external origins for
// styles and fonts. Self-hosting removes both problems and lets the CSP be
// locked to 'self'.
//
// The font families, weights and unicode-ranges are copied from Google's own
// stylesheet, so rendering is byte-identical to what the site rendered before.
// Only the subsets the site cannot use are dropped (see KEEP_SUBSETS): the UI
// ships Arabic and English only.
//
// Re-run with:  node scripts/fetch-fonts.mjs
// It is not part of the build. Fonts are committed; the build stays offline.

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const FONT_DIR = resolve(HERE, '../src/assets/fonts')
const CSS_OUT = resolve(HERE, '../src/styles/fonts.css')

// The same families and weights the old <link> in index.html requested.
const GOOGLE_CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700' +
  '&family=Inter:wght@400;500;600;700;800' +
  '&family=Cairo:wght@400;500;600;700;800' +
  '&display=swap'

// A modern desktop UA is required or Google serves legacy ttf instead of woff2.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

// The site is Arabic + English. Cyrillic, Greek and Vietnamese subsets can
// never be selected by the unicode-range matcher here, so shipping them would
// be dead weight in the repository.
const KEEP_SUBSETS = new Set(['arabic', 'latin', 'latin-ext'])

/** Splits Google's stylesheet into one record per @font-face block. */
function parseFontFaces(css) {
  const faces = []
  const blockRe = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g
  let m
  while ((m = blockRe.exec(css)) !== null) {
    const [, subset, body] = m
    const field = (name) => {
      const hit = new RegExp(`${name}:\\s*([^;]+);`).exec(body)
      return hit ? hit[1].trim() : null
    }
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(body)
    if (!url) continue
    faces.push({
      subset,
      family: field('font-family').replace(/^['"]|['"]$/g, ''),
      style: field('font-style') ?? 'normal',
      weight: field('font-weight') ?? '400',
      unicodeRange: field('unicode-range'),
      url: url[1],
    })
  }
  return faces
}

/** Stable, collision-free local filename for a face. */
function localName(face) {
  return `${face.family}-${face.weight}-${face.style}-${face.subset}.woff2`.replace(/\s+/g, '')
}

async function main() {
  console.log('Fetching stylesheet from Google Fonts…')
  const res = await fetch(GOOGLE_CSS_URL, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`Google Fonts CSS request failed: HTTP ${res.status}`)
  const css = await res.text()

  const all = parseFontFaces(css)
  if (all.length === 0) throw new Error('Parsed zero @font-face blocks — the CSS format changed.')
  const faces = all.filter((f) => KEEP_SUBSETS.has(f.subset))
  console.log(`Parsed ${all.length} faces, keeping ${faces.length} (${[...KEEP_SUBSETS].join(', ')}).`)

  await mkdir(FONT_DIR, { recursive: true })

  let bytes = 0
  for (const face of faces) {
    const fileRes = await fetch(face.url, { headers: { 'User-Agent': UA } })
    if (!fileRes.ok) throw new Error(`Font download failed (${face.url}): HTTP ${fileRes.status}`)
    const buf = Buffer.from(await fileRes.arrayBuffer())
    bytes += buf.length
    await writeFile(resolve(FONT_DIR, localName(face)), buf)
    console.log(`  ${localName(face)} — ${(buf.length / 1024).toFixed(1)} KB`)
  }

  const header = `/* GENERATED by scripts/fetch-fonts.mjs — do not hand-edit.
   Self-hosted copies of the same Google Fonts the site already used
   (Cairo, Inter, Fraunces), so no third-party origin is contacted at
   runtime and the Content-Security-Policy can stay locked to 'self'.
   Families, weights and unicode-ranges are Google's own values, so text
   renders exactly as before.

   Cairo: SIL Open Font License 1.1
   Inter: SIL Open Font License 1.1
   Fraunces: SIL Open Font License 1.1 */\n\n`

  const body = faces
    .map((face) =>
      [
        `/* ${face.subset} */`,
        `@font-face {`,
        `  font-family: '${face.family}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        `  font-display: swap;`,
        `  src: url('../assets/fonts/${localName(face)}') format('woff2');`,
        face.unicodeRange ? `  unicode-range: ${face.unicodeRange};` : null,
        `}`,
      ]
        .filter(Boolean)
        .join('\n'),
    )
    .join('\n\n')

  await writeFile(CSS_OUT, header + body + '\n')
  console.log(`\nWrote ${CSS_OUT}`)
  console.log(`Total font payload: ${(bytes / 1024).toFixed(0)} KB across ${faces.length} files.`)
}

main().catch((err) => {
  console.error(err.message)
  process.exit(1)
})
