// Phase 13.5d — Destination Tourism Insights: runtime read-side of the
// build-time snapshot generated by scripts/generate-tourism-insights.mjs.
// Lazy-loaded exactly like data/travelCostIndex.ts / data/cities.ts: a
// single shared promise, dynamically imported so Vite code-splits the
// snapshot into its own chunk, load failure resolves to `null` (never
// throws). No network call happens here — this only reads the already-
// committed, already-validated JSON file.
import { isExcludedIso2 } from './excludedCountries';
import type { DestinationTourismEntry, TourismInsightsSnapshot, TourismObservation, YoyGrowth } from './types';

let snapshotPromise: Promise<TourismInsightsSnapshot | null> | null = null;

function loadSnapshot(): Promise<TourismInsightsSnapshot | null> {
  if (!snapshotPromise) {
    snapshotPromise = import('./generated/tourismInsights.json')
      .then((mod) => mod.default as unknown as TourismInsightsSnapshot)
      .catch((err: unknown) => {
        console.error('Failed to load the tourism insights snapshot; the section will render nothing.', err);
        return null;
      });
  }
  return snapshotPromise;
}

/** Resolves the dynamic Tourism Insights entry for a country, by its
 *  ISO2 `countryCode` — the SAME code space as CatalogEntry.countryCode.
 *  Returns undefined (never a guess) when: the snapshot failed to load,
 *  has never been generated (entries: []), this country has neither
 *  series, or the country is excluded. */
export async function getTourismInsights(countryCode: string): Promise<DestinationTourismEntry | undefined> {
  // Defense-in-depth, same 3rd independent layer as
  // travelCostIndex.ts's getTravelCostIndex().
  if (isExcludedIso2(countryCode)) return undefined;

  const snapshot = await loadSnapshot();
  if (!snapshot) return undefined;
  return snapshot.entries.find((entry) => entry.countryCode === countryCode);
}

/** Pure, deterministic: the observation with the numerically latest
 *  `period`, or undefined for an empty/undefined series. Never guesses
 *  an out-of-series "current" value. */
export function getLatestObservation(series: TourismObservation[] | undefined): TourismObservation | undefined {
  if (!series || series.length === 0) return undefined;
  return series.reduce((latest, obs) => (Number(obs.period) > Number(latest.period) ? obs : latest));
}

/** Pure, deterministic year-over-year growth from the two most recent
 *  CONSECUTIVE observations in a series (numeric years exactly 1 apart)
 *  — never computed across a gap (e.g. 2019 -> 2022 skipping missing
 *  years), since that would silently misrepresent a multi-year change
 *  as a single year's growth. Returns undefined (never 0, never a
 *  guess) when: fewer than 2 observations, the two latest are not
 *  consecutive years, or the previous value is <= 0 (an undefined or
 *  infinite percentage). */
export function computeYoyGrowth(series: TourismObservation[] | undefined): YoyGrowth | undefined {
  if (!series || series.length < 2) return undefined;
  const sorted = [...series].sort((a, b) => Number(a.period) - Number(b.period));
  const current = sorted[sorted.length - 1];
  const previous = sorted[sorted.length - 2];
  if (Number(current.period) - Number(previous.period) !== 1) return undefined;
  if (previous.value <= 0) return undefined;
  const percent = ((current.value - previous.value) / previous.value) * 100;
  return { currentPeriod: current.period, previousPeriod: previous.period, percent };
}

/** Compact, locale-agnostic large-number formatting for metric cards
 *  (e.g. 14200000 -> "14.2M", 12800000000 -> "12.8B"). Never rounds away
 *  the magnitude (thousands stay as plain numbers, no fake "0.0K"
 *  precision loss for small values). Deterministic; not
 *  Intl-locale-dependent so EN/AR render the same digits (only the
 *  surrounding label text is translated). */
export function formatCompactNumber(value: number): string {
  const abs = Math.abs(value);
  const sign = value < 0 ? '-' : '';
  if (abs >= 1_000_000_000) return `${sign}${(abs / 1_000_000_000).toFixed(1)}B`;
  if (abs >= 1_000_000) return `${sign}${(abs / 1_000_000).toFixed(1)}M`;
  if (abs >= 1_000) return `${sign}${(abs / 1_000).toFixed(1)}K`;
  return `${sign}${Math.round(abs)}`;
}
