// Phase 13.5c — Dynamic Travel Cost Index: runtime read-side of the
// build-time snapshot generated by scripts/generate-travel-cost-index.mjs
// (see scripts/lib/travelCostIndexIngest.mjs for the shared classify
// logic this mirrors, and TRAVEL_COST_INDEX.md for the full writeup).
// Lazy-loaded exactly like data/cities.ts / data/airports.ts: a single
// shared promise, dynamically imported so Vite code-splits the snapshot
// into its own chunk, and a load failure resolves to `null` (never
// throws) so callers fall back cleanly. No network call happens here —
// this only ever reads the already-committed, already-validated JSON
// file; the app never depends on World Bank/OECD/IMF being reachable at
// runtime.
import { isExcludedIso2 } from './excludedCountries';
import type { TravelCostIndexEntry, TravelCostSnapshot, TravelCostTier } from './types';

/** Same thresholds as scripts/lib/travelCostIndexIngest.mjs's
 *  CLASSIFICATION_THRESHOLDS/classifyPriceLevelIndex — duplicated here
 *  (not imported: the generation script is plain Node ESM with no TS
 *  loader, and this module is bundled TS/ESM for the browser) rather
 *  than shared, but travelCostIndexIngest.test.mjs and this file's own
 *  tests both assert the exact boundary values below, so a drift
 *  between the two would be caught immediately. 100 = same general
 *  price level as the US (this indicator's own baseline). */
const CLASSIFICATION_THRESHOLDS = {
  low: 60,
  moderate: 90,
  high: 115,
};

/** Pure, deterministic: the same priceLevelIndex always returns the
 *  same tier. See CLASSIFICATION_THRESHOLDS' doc comment in
 *  travelCostIndexIngest.mjs for why these specific boundaries. */
export function classifyPriceLevelIndex(priceLevelIndex: number): TravelCostTier {
  if (priceLevelIndex < CLASSIFICATION_THRESHOLDS.low) return 'low';
  if (priceLevelIndex < CLASSIFICATION_THRESHOLDS.moderate) return 'moderate';
  if (priceLevelIndex < CLASSIFICATION_THRESHOLDS.high) return 'high';
  return 'veryHigh';
}

let snapshotPromise: Promise<TravelCostSnapshot | null> | null = null;

function loadSnapshot(): Promise<TravelCostSnapshot | null> {
  if (!snapshotPromise) {
    snapshotPromise = import('./generated/travelCostIndex.json')
      .then((mod) => mod.default as unknown as TravelCostSnapshot)
      .catch((err: unknown) => {
        console.error('Failed to load the travel cost index snapshot; falling back to static cost guidance.', err);
        return null;
      });
  }
  return snapshotPromise;
}

/** Resolves the dynamic Travel Cost Index entry for a country, by its
 *  ISO2 `countryCode` — the SAME code space as CatalogEntry.countryCode,
 *  never re-derived or guessed. Returns undefined (never a guess, never
 *  a fabricated value) when: the snapshot failed to load, the snapshot
 *  has never been generated yet (entries: []), or this specific country
 *  simply isn't in the source dataset's coverage. Callers (e.g.
 *  AccommodationInfo.tsx) MUST fall back to the existing static
 *  Destination.costLevel guidance in every one of those cases — never
 *  present the fallback as if it were freshly sourced. */
export async function getTravelCostIndex(countryCode: string): Promise<TravelCostIndexEntry | undefined> {
  // Defense-in-depth, same principle as the ingestion script's own
  // exclusion mirror: excludedCountries.ts (via WORLD_CATALOG) already
  // guarantees no CatalogEntry with an excluded countryCode exists for a
  // caller to pass in here, and validateEntries() already guarantees
  // the real generated snapshot never contains one — this check is a
  // third, independent layer so this function can never surface an
  // excluded country's data even if either of those were ever violated
  // (a bad manual edit to the snapshot file, a future caller that
  // doesn't go through WORLD_CATALOG, etc.).
  if (isExcludedIso2(countryCode)) return undefined;

  const snapshot = await loadSnapshot();
  if (!snapshot) return undefined;
  return snapshot.entries.find((entry) => entry.countryCode === countryCode);
}
